### ISSUE TITLE
Fix CMake rpath on OSX

### ISSUE THREAD

**Issue by soumagne** [mercury-hpc/mercury#125]
Previous e-mail from Chuck:

> What I'm looking for is to be able to install mercury where ever I want to and to not have to set LD_LIBRARY_PATH or DYLD_LIBRARY_PATH environment variables.

> On linux you can easily achieve this by setting "CMAKE_INSTALL_RPATH_USE_LINK_PATH" to TRUE.   that causes it to set the rpath in the binary to match the linked libraries on
the command line.

> On OSX the "CMAKE_INSTALL_RPATH_USE_LINK_PATH" TRUE setting only works if you have CMAKE_MACOSX_RPATH=1.
 
> Looks like cmake added @ rpath support in 2.8.12, but it was switched off by default.   In 3.0 they made it on by default and added policy CMP0042.

> It looks like the intent of the mercury/CMakeLists.txt is to disable @ rpath support by default as long as 2.8.5 is the cmake_minimum_required() and then switch it on by default when the cmake_minimum_required() is 2.8.12 or better.

> Its not clear to me what could break if you turn on @ rpath support if you've got it.   

> The impression I get is that if you don't use @ rpath support (the current state in mercury), then it would be better to use full paths in the libary install name (which is what cci and bmi are doing). i believe that would involve setting the INSTALL_NAME_DIR property for each library target to ${CMAKE_INSTALL_PREFIX}/lib, but i can't find any instances of INSTALL_NAME_DIR in the mercury srcs.

> https://cmake.org/cmake/help/v3.0/prop_tgt/INSTALL_NAME_DIR.html#prop_tgt:INSTALL_NAME_DIR

**Comment by soumagne** [comment]
@chuckcranor please give it a try and let me know if that fixes your problem

**Comment by chuckcranor** [comment]
I tested it, it works.   It does put an extra "/" in the install name:

> otool -L libmercury.dylib 
libmercury.dylib:
        @rpath//libmercury.0.8.9.dylib (compatibility version 0.8.9, current version 0.8.9)

you could apply this:
diff --git a/CMakeLists.txt b/CMakeLists.txt
index cfe0ad8..ae308ce 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -73,7 +73,7 @@ if(APPLE)
   endif()
   unset(MACOSX_APP_INSTALL_PREFIX CACHE)
 
-  set(CMAKE_INSTALL_NAME_DIR "@rpath/")
+  set(CMAKE_INSTALL_NAME_DIR "@rpath")
   mark_as_advanced(
     CMAKE_OSX_ARCHITECTURES
     CMAKE_OSX_DEPLOYMENT_TARGET
