### ISSUE TITLE
CLOCK_MONOTONIC_RAW not defined at nersc edison

### ISSUE THREAD

**Issue by zhengqmark** [mercury-hpc/mercury#140]
Looks like nersc edison's linux doesn't have CLOCK_MONOTONIC_RAW defined so mercury cannot be compiled on it.

Is it possible to use a different but close enough clock type to replace CLOCK_MONOTONIC_RAW when CLOCK_MONOTONIC_RAW is absent ?  :-)

zhengq@edison10:~/deltafs-umbrella/build> gcc --version
gcc (GCC) 6.1.0 20160427 (Cray Inc.)
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

zhengq@edison10:~/deltafs-umbrella/build> uname -a
Linux edison10 3.0.101-0.46-default #1 SMP Wed Dec 17 11:04:10 UTC 2014 (8356111) x86_64 x86_64 x86_64 GNU/Linux

/global/homes/z/zhengq/deltafs-umbrella/build/mercury-prefix/src/mercury/src/util/mercury_time.c: In function 'hg_time_get_current':
/global/homes/z/zhengq/deltafs-umbrella/build/mercury-prefix/src/mercury/src/util/mercury_time.c:112:23: error: 'CLOCK_MONOTONIC_RAW' undeclared (first use in this function)
     if (clock_gettime(CLOCK_MONOTONIC_RAW, &tp)) {
                       ^~~~~~~~~~~~~~~~~~~
/global/homes/z/zhengq/deltafs-umbrella/build/mercury-prefix/src/mercury/src/util/mercury_time.c:112:23: note: each undeclared identifier is reported only once for each function it appears in
make[6]: *** [src/util/CMakeFiles/mercury_util.dir/mercury_time.c.o] Error 1
make[5]: *** [src/util/CMakeFiles/mercury_util.dir/all] Error 2
make[4]: *** [all] Error 2
make[3]: *** [mercury-prefix/src/mercury-stamp/mercury-build] Error 2
make[2]: *** [CMakeFiles/mercury.dir/all] Error 2
make[1]: *** [CMakeFiles/deltafs.dir/rule] Error 2
make: *** [deltafs] Error 2

**Comment by soumagne** [comment]
OK I'll get that fixed. Thanks.
