### ISSUE TITLE
Expose reference count increment

### ISSUE THREAD

**Issue by soumagne** [mercury-hpc/mercury#144]
Original message from Xuezhao:
> Just to discuss with you about one small issue about HG internal refcount.
>
> Now HG_Get_input implemented as  calling hg_core_incr_ref, HG_Core_get_input and some other core APIs.
>
> As in Cart we added an internal header above HG and we want to unpack the RPC request header first and then unpack the boy when serving a RPC request, so we use the HG_Core_ APIs.
One problem is that the HG_Core_get_input does not take refcount, so we will meet a problem later when calling HG_Free_input/HG_Destroy as it will cause refcount issue.
>
> We could have some hacking in CaRT to avoid the refcount issue, at the other hand do you think does it reasonable to move the calling of hg_core_incr_ref to be inside HG_Core_get_input?
(one related change is adding a hg_core_destroy to hg_set_input, it seems reasonable as it can protect the handle be valid during hg_set_input).

It seems that exposing the reference count increment function would just solve the issue.

**Comment by soumagne** [comment]
@liuxuezhao Let me know if you have any more problems.

**Comment by liuxuezhao** [comment]
@soumagne thanks very much, it looks good, I'll make some change to cart to use it.
