### ISSUE TITLE
Non-registered RPC requests prevent clean shutdown

### ISSUE THREAD

**Issue by soumagne** [mercury-hpc/mercury#149]
Original e-mail from Shane:
> Yes, this issue is caused by a process that has not yet called
MERCURY_REGISTER for RPC operations that it is already starting to
receive from other processes. When that happens, you get the following
output, but I also notice that the process that received the RPCs before
registering them hangs when calling HG_Context_destroy, as well.
> ```
> HG: Error in /home/shane/software/mercury/src/mercury_core.c:1656
>  # hg_core_process(): Could not find RPC ID in function map
>HG: Error in /home/shane/software/mercury/src/mercury_core.c:2128
>  # hg_core_trigger_entry(): Could not process handle
>HG: Error in /home/shane/software/mercury/src/mercury_core.c:2065
>  # hg_core_trigger(): Could not trigger completion entry
>HG: Error in /home/shane/software/mercury/src/mercury_core.c:3039
>  # HG_Core_trigger(): Could not trigger callbacks
>```
> Can Mercury just throw out the incoming requests that it can't find a
matching RPC ID for? It seems like its probably saving state on them
that is preventing Mercury from shutting down cleanly, unless something
else is going on.

**Comment by soumagne** [comment]
I would agree with simply throwing a warning if the request is not registered yet (instead of throwing an error) and ignore the request... or that could also be a configurable option?

**Comment by shanedsnyder** [comment]
My thoughts are that a warning message (i.e., not an unrecoverable error) is sufficient for this issue. Maybe the default behavior is to print the warnings, but if you want you could add a configure option to suppress them? 

I think the main thing is just ensuring that an issue like this doesn't cause deadlock when shutting down Mercury. There aren't really any mechanisms to prevent processes from sending RPCs to other processes which may have not finished registering them yet (using MERCURY_REGISTER macro), so from a Mercury users perspective, the problem isn't really avoidable.

**Comment by soumagne** [comment]
Thinking a little more about it, we should in that case respond back to the client with an error I believe... unless it's a one-way RPC and we can just simply ignore it.

**Comment by carns** [comment]
That might be helpful, if there is a Mercury-level header in the nack that we can use to indicate a "no such rpc handler" and short circuit the user-defined rpc ack decoder.

**Comment by soumagne** [comment]
OK, this is now fixed in 299ee56143b93fb6985edc59972720e2e6c75463 along with #108. Everything will be merged to master in the coming days.
