### ISSUE TITLE
mercury not populating pkg-config sufficiently

### ISSUE THREAD

**Issue by roblatham00** [mercury-hpc/mercury#151]
I've configured mercury to use CCI

Now I try to build 'margo' but it complains about missing cci symbols and missing clock_gettimeofday symbols.

I can add cci and -ltr to margo's configure by hand, but shouldn't mercury pkg-config --libs advertise those libraries?

**Comment by soumagne** [comment]
can you please show me your pkg-config file? 
here is what I have:
```
# This gives access to the mercury header files
prefix=/opt/mercury/0.9.0
exec_prefix=/opt/mercury/0.9.0
libdir=/opt/mercury/0.9.0/lib
includedir=/opt/mercury/0.9.0/include

Name: mercury
Description: RPC Library for High-Performance Computing
Version: 0.9.0
URL: http://trac.mcs.anl.gov/projects/mercury
Requires:
Libs: -L${libdir}  -lmercury_hl_debug -lmercury_debug -lna_debug -lmercury_util_
debug
Libs.private:  -L/opt/cci/default/lib -lcci -lpthread -lrt
Cflags: -I${includedir}  -I/usr/include
```

**Comment by soumagne** [comment]
you might actually need to do `pkg-config --libs --static` ?

**Comment by roblatham00** [comment]
I'm using 'spack' to manage the dependencies in the mercury suite, so the path names are ridiculously long.  However, my pkg-config matches yours:

`cat /blues/gpfs/home/robl/src/spack/opt/spack/linux-centos6-x86_64/gcc-4.7.2/mercury-master-aa3qmpjgk77an2uajntyhfljvxocvacw/lib/pkgconfig/mercury.pc`
```
# This gives access to the mercury header files
prefix=/blues/gpfs/home/robl/src/spack/opt/spack/linux-centos6-x86_64/gcc-4.7.2/mercury-master-aa3qmpjgk77an2uajntyhfljvxocvacw
exec_prefix=/blues/gpfs/home/robl/src/spack/opt/spack/linux-centos6-x86_64/gcc-4.7.2/mercury-master-aa3qmpjgk77an2uajntyhfljvxocvacw
libdir=/blues/gpfs/home/robl/src/spack/opt/spack/linux-centos6-x86_64/gcc-4.7.2/mercury-master-aa3qmpjgk77an2uajntyhfljvxocvacw/lib
includedir=/blues/gpfs/home/robl/src/spack/opt/spack/linux-centos6-x86_64/gcc-4.7.2/mercury-master-aa3qmpjgk77an2uajntyhfljvxocvacw/include

Name: mercury
Description: RPC Library for High-Performance Computing
Version: 0.9.0
URL: http://trac.mcs.anl.gov/projects/mercury
Requires:
Libs: -L${libdir}  -lmercury_hl -lmercury -lmchecksum -lna -lmercury_util
Libs.private:  -L/blues/gpfs/home/robl/src/spack/opt/spack/linux-centos6-x86_64/gcc-4.7.2/cci-2.0-w5rvaukl5qpe5qxsc6yrprmousa65ejl/lib -lcci -lpthread -lrt
Cflags: -I${includedir}  -I/blues/gpfs/home/robl/src/spack/opt/spack/linux-centos6-x86_64/gcc-4.7.2/boost-1.63.0-ds3fbl3vdsk6u5soirxcdoe3e6dw3iwx/include -I/blues/gpfs/home/robl/src/spack/opt/spack/linux-centos6-x86_64/gcc-4.7.2/cci-2.0-w5rvaukl5qpe5qxsc6yrprmousa65ejl/include
```

Thanks for the tip about `--libs --static`: it does give the correct library list:

`$  pkg-config --libs --static mercury`
```
-L/blues/gpfs/home/robl/src/spack/opt/spack/linux-centos6-x86_64/gcc-4.7.2/mercury-master-aa3qmpjgk77an2uajntyhfljvxocvacw/lib -L/blues/gpfs/home/robl/src/spack/opt/spack/linux-centos6-x86_64/gcc-4.7.2/cci-2.0-w5rvaukl5qpe5qxsc6yrprmousa65ejl/lib -lmercury_hl -lmercury -lmchecksum -lna -lmercury_util -lcci -lpthread -lrt
 ```

It seems that at least on this Centos-6.8 machine the private libraries are not private?  If I do not explicitly add `-lcci -lrt` to margo's configure, I get undefined cci symbols.

**Comment by carns** [comment]
The convention (in theory anyway) is supposed to be that when you are dynamic linking, the dynamic libraries will track their own dependencies (via rpath etc.) without you specifying all of the libraries at the top level with -l.  If you are using stastic linking, then you do have to list them all.

Is this with static libraries or dynamic libraries?

**Comment by roblatham00** [comment]
Ah-ha!  looks like I failed to ask spack to build shared libraries, so my 'lib' dir is full of .a files.   Let me rebuild the stack and confirm shared libraries do the right thing.

**Comment by roblatham00** [comment]
OK, that did the trick.  thanks for the help, and sorry I ever impinged on the fine reputation of mercury!

**Comment by soumagne** [comment]
:wink:  no worries, great, thanks! I realized that I have to update the URL in the pkg-config file though.
