### ISSUE TITLE
NA CCI: Tcp transport randomly hangs

### ISSUE THREAD

**Issue by soumagne** [mercury-hpc/mercury#152]
Original message from Chuck:
>cci+tcp has been broken since a commit done back on 21-Nov-2016.
>
>Mercury uses the "cci_get_event(e, &event)" API to receive event 
>notifications from cci (e.g. events like send, recv, connect req,
>connect, accept).   The first arg "e" is the cci endpoint structure,
>and the second arg "&event" is a pointer where the next event 
>structure from cci is returned.   
>
>The cci library owns the returned event structure (cci malloc'd
>it earlier), so when Mercury is done processing the event, Mercury
>returns it to cci with the call: "cci_return_event(event)" ...
>Internally, the cci_return_event() function just adds the event
>back to a free event list for reuse (in cci+tcp this is done
>in ctp_tcp_return_event() -- adding the event to the idle rx
>event list using "tcp_put_rx(rx)").
> 
>Unfortunately, the commit from 21-Nov-2016 (c37fa323fe in git)
>added an additional call to "tcp_put_rx(rx)" in the cci_accept()
>path, when you get a connection request.   This results in the
>event structure getting added to the same list twice, breaking the
>list data structure.   the sequence is:
>  
>    1. Mercury's na_cci_progress() calls cci_get_event() and gets 
>       a CCI_EVENT_CONNECT_REQUEST event structure.  This gets 
>       routed to Mercury's "handle_connect_request()" function.
>    
>    2. "handle_connect_request()" calls "cci_accept(event, ...)" to
>       accept the request.  This maps to ctp_tcp_accept() in the 
>       tcp plugin.  The accept function sends a reply to the 
>       accept (TCP_MSG_CONN_REPLY), and then with the change in
>       c37fa323fe it puts the event on the free list (idle_rx)
>       with a call to tcp_put_rx(rx).
>
>    3. Control returns to Mercury's na_cci_progress().  As 
>       Mercury has completed processing on the event, it calls
>       cci_return_event(event) to return the event to cci.
>       This maps to ctp_tcp_return_event(event) in the tcp
>       plugin.   This function then calls tcp_put_rx(rx) to
>       put the event on the free list (idle_rx) --- but the
>       event is already on that free list (from step 2, above), 
>       so the attempt to add it again breaks the list data structure 
>       (a tailq).
>
>Once the idle_rx list is damaged, cci+tcp may or may not function
>well enough to continue for simple programs (e.g. like when
>my test program serialized its requests).   It depends the
>timing of arrivals of future requests.  I think anything beyond
>simple test programs are likely to fail.

**Comment by soumagne** [comment]
@scottatchley Hi Scott, we've had random failures with cci+tcp tests recently and Chuck (@chuckcranor) has noticed the issue above in the CCI tcp plugin. Could you please have a look?

**Comment by scottatchley** [comment]
Hi Jerome,

Yes, I will take a look.

I also just got access today to our XC40 (I just learned that we had one) so I can debug RMA with GNI.

Scott

**Comment by scottatchley** [comment]
Removed, committed, and pushed to github. Let me know if that is the wrong email.

commit 3ab663e0d4447be00f46027e18edd370c491f41b
Author: Scott Atchley <atchleyes@ornl.gov>
Date:   Mon Feb 6 17:57:15 2017 -0500

    tcp: revert c37fa323fe
    
    The rx is not leaked. It is returned when the caller returns the
    CONNECT_REQUEST event.
    
    Reported by Chuck Cranor <chuck@ece.cmu.edu>

**Comment by soumagne** [comment]
Scott, thanks for the quick reply, great that seems much better, thanks!
