### ISSUE TITLE
hg_poll_destroy(): Poll set non empty

### ISSUE THREAD

**Issue by carns** [mercury-hpc/mercury#156]
I'm getting the following error on both the client side and server side when shutting down Mercury, using the Margo library atop it, and configuring Mercury to include no transports except the na_sm one:

```
# HG Util -- Error -- /home/pcarns/working/src/mochi/mercury/src/util/mercury_poll.c:121
 # hg_poll_destroy(): Poll set non empty
# NA -- Error -- /home/pcarns/working/src/mochi/mercury/src/na/na_sm.c:2719
 # na_sm_finalize(): hg_poll_destroy() failed
# HG -- Error -- /home/pcarns/working/src/mochi/mercury/src/mercury_core.c:913
 # hg_core_finalize(): Could not finalize NA interface
# HG -- Error -- /home/pcarns/working/src/mochi/mercury/src/mercury_core.c:2373
 # HG_Core_finalize(): Cannot finalize HG core layer
```

The communication leading up to that point worked fine.  Is this something that I am doing wrong at the API level, or is this an issue inside Mercury?

**Comment by carns** [comment]
Looking in a debugger I can see that there are two poll_sets being manipulated during the run.  One of them has exactly one hg_poll_add() and a matching hg_poll_remove().  The other one has 3 hg_poll_add() calls but only 1 hg_poll_remove() call.

**Comment by carns** [comment]
I was able to fix the problem on the client side by adding a missing HG_addr_free() call in the application (to match an earlier addr_lookup()).  I should have been doing this all along, but it is more obvious now that the is necessary to remove fds from the poll set :)

I'm still having a the "Poll set non empty" problem on the server side, though, and I don't believe that it is calling an explicit addr_lookup() like the client is.

**Comment by carns** [comment]
It looks like at least one of the extra fd's on the server side is being added to a poll set by way of the na_sm_progress_accept() call path, which in turn calls na_sm_poll_register(), but I'm not sure how that fd is supposed to get back out of the poll set after that.

**Comment by soumagne** [comment]
Ah ok yes actually Yulu had that problem and that's why I entered the issue: https://github.com/mercury-hpc/mercury/issues/150

**Comment by soumagne** [comment]
Hmm all addresses on the server should be freed unless there is still a reference to it, which Addr calls are you making on the server?

**Comment by carns** [comment]
Ok.  I walked through na_sm_finalize(), and I can see that it is indeed iterating the accepted_addr_queue and trying to free the right address (which would clear it from the poll set).  The na_sm_addr_free() is returning early, though, because the ref count on the address has not hit zero.

I may have a problem in the timing of how I am shutting down the service via an RPC.  Maybe the RPC handler hasn't fully completed and cleaned up before I start executing the shutdown steps.  I'll check.

**Comment by soumagne** [comment]
Ah I see, that could be possible, well anyway I think that's another reason for having #150. I'm thinking of just having a counter per na_class that gets incrememented on creation and decremented when an addr is freed. Addresses get created after a recv_unexpected call and freed when we are done with the handle.

**Comment by soumagne** [comment]
Although NA_Finalize should never be called if something has not completed yet... so maybe that's something else....

**Comment by carns** [comment]
Ok, I'm confused :)

Two more pieces of data:
* I have multiple concurrent RPCs in flight to the same na_sm addr at an earlier point in this test
* The na_complete_sm() function causes the ref_count for that addr to go rather high (to 5 in this case) because of the hg_atomic_incr32() in the NA_CB_RECV_UNEXPECTED switch case
* na_sm_addr_free() is called later, but never gets the ref count low enough before finalize

Is there some other code path that is supposed to decrement the addr refcount that I'm not seeing?  I don't see how addr_free() will be called enough times to get it to zero.

If I comment out the hg_atomic_incr32() call in na_complete_sm() then the error goes away for me, but I'm not sure I really understand what's going on here, so that might not be a real fix.

**Comment by carns** [comment]
That's definitely not the right fix exactly; if I simply comment out that inc32 then addr_free() gets called twice for that address even though the ref_count stays at 1 (meaning that the second addr_free() is making the ref_count go negative, and probably is corrupting memory).

**Comment by carns** [comment]
Maybe the na_sm add ref counting is right, but I'm having a problem with the handle ref counting above it.  If the handle ref count never hits zero, then it will never call free on the underlying addr.  If I add printfs to hg_core_destroy() and hg_core_reset_post() I can see that there are handles that never get past a ref count of 1.  If they were to hit zero maybe they would trigger enough addr_frees to release the na_sm addr.

Still not really sure if this is a problem in my code or something I am triggering in Mercury.

**Comment by carns** [comment]
Wow, that was painful.  This was a problem in my code.  I had an RPC handler that was not calling HG_Free_input().  This prevented the handle ref count from being decremented, which prevented the handle destroy from calling the addr free function, which prevented its ref count from being decremented, which ultimately led to too many fds in the poll set, and thus the error.

Ultimately the error msg was a good thing because it revealed a bug in this test program that I was not aware of before, it just took me a long time to debug.

Sorry about the github noise.

**Comment by soumagne** [comment]
I see, so that's what I was expecting then, recv_unexpected creates an address, which is the reason why the refcount is incremented in na_sm. The address returned from recv_unexpected though is attached to the handle in mercury_core.c line 1483 and then freed with the handle or when the handle is reposted, line 1895.

**Comment by soumagne** [comment]
Oh sorry I just see your message now and I was going to say that it means that the refcount to the handle is not decremented :)

**Comment by soumagne** [comment]
I wonder how we could prevent that situation from happening, or at least to tell the user that something has not been freed...

**Comment by carns** [comment]
Maybe just a safety check at finalize time if there are any handles left that were never fully destroyed?  I think in this case I would have saved time if I had known to look for a resource leak at that level instead of the NA level.

**Comment by soumagne** [comment]
Yes sounds good to me, I guess we can do the same check as for addresses (and for anything that is created in general)
