### ISSUE TITLE
na+sm protocol returns incorrect addrs when looking up addrs concurrently

### ISSUE THREAD

**Issue by shanedsnyder** [mercury-hpc/mercury#159]
If I issue concurrent address lookups using na+sm and Argobots ULTs, the addresses get jumbled up on the way out. For instance, say I issue 2 concurrent address lookups for processes with addresses 'na+sm:3000/0' & 'na+sm:3001/0' and Mercury returns corresponding hg_addr_t structures for these addresses. If I send an RPC to the addr returned by the lookup for process 'na+sm:3000/0', it's actually ending up at process 'na+sm:3001/0'. I can confirm this is what's happening by using 'HG_Addr_to_string' to verify the output address being returned by lookup does not match the input string to the call.

I can workaround the issue for now by issuing each addr_lookup serially, which seems to imply the issue is caused by concurrent lookups. I do not see this issue with cci+tcp, so I think it might be specific to the shared memory protocol. That said, shared memory transport should be much quicker and there's a chance it could be exposing a race condition that is not triggered in other protocols in my testing.

**Comment by soumagne** [comment]
@shanedsnyder Let me know if this is fixed

**Comment by shanedsnyder** [comment]
Just checked and it works now. Thanks for the fix!
