### ISSUE TITLE
Mercury still tries to build na_sm after failing to detect process_vm_readv()

### ISSUE THREAD

**Issue by carns** [mercury-hpc/mercury#166]
Reproduced on cooley.alcf.anl.gov with origin/master and the following cmake options:

```
cmake -DNA_USE_CCI:BOOL=ON -DMERCURY_USE_BOOST_PP:BOOL=ON -DCMAKE_INSTALL_PREFIX=/home/carns/working/install-cooley/ -DBoost_NO_BOOST_CMAKE=TRUE -DMERCURY_USE_CHECKSUMS:BOOL=OFF -DBUILD_SHARED_LIBS:BOOL=ON -DMERCURY_USE_SELF_FORWARD:BOOL=ON ../
```

cmake produces this output:

```
-- Looking for process_vm_readv
-- Looking for process_vm_readv - not found
CMake Warning at src/na/CMakeLists.txt:156 (message):
  Platform does not meet NA SM requirements.
```

Running make then produces this:

```
[ 59%] Building C object src/na/CMakeFiles/na.dir/na_sm.c.o
/home/carns/working/src/mochi/mercury/src/na/na_sm.c: In function ‘na_sm_setup_shm’:
/home/carns/working/src/mochi/mercury/src/na/na_sm.c:1294: error: ‘NA_SM_SHM_PREFIX’ undeclared (first use in this function)
...
```

Should cmake automatically disable na_sm in this case?  The outcome of the cmake check is correct, this system definitely lacks  the required headers for the CMA system calls.

**Comment by carns** [comment]
The workaround is to just add ```-DNA_USE_SM:BOOL=OFF``` to the cmake options so this isn't a high priority; it can be fixed manually.

**Comment by soumagne** [comment]
OK yes I think in this case it should be off. It should not try to build the plugin if it does not meet the requirements... so it looks like there is a problem somewhere.

**Comment by roblatham00** [comment]
It looks like you tried to make mercury/src/na/na_sm.c  conditionally
compile,  but the 'nread' variable is used outside of a NA_SM_HAS_CMA
#ifdef block.

**Comment by soumagne** [comment]
Hmm ok I will get to it later today
