### ISSUE TITLE
NA OFI: cannot progress when reaching 256 RPCs

### ISSUE THREAD

**Issue by soumagne** [mercury-hpc/mercury#170]
Reported by Tang, ofi + tcp hangs when reaching max handles:
>  it works ok for tests with only a few RPCs but the server stops responding after it receives 255 RPC messages. 
> E.g. 
>
>      ./bin/pdc_server.exe &
> 
>      ./bin/create_obj_scale -r 255     // runs ok
> 
>      ./bin/create_obj_scale -r 256     // server hangs

**Comment by liuxuezhao** [comment]
just FYI by cart/daos usage over ofi plugin, we can handle millions of RPC over ofi+tcp.

**Comment by soumagne** [comment]
@liuxuezhao yes I know and the tests also passed when sending large numbers of RPCs. I suspect this only happens when no progress is made on the server. I should probably modify the title but I would need to know what is happening first...
