### ISSUE TITLE
NA OFI: tag mismatch error / multiple targets

### ISSUE THREAD

**Issue by soumagne** [mercury-hpc/mercury#171]
Reported by Tang using ofi+tcp:
> When I launch more than one server, when the clients start to send RPCs to them, I got the following errors, any idea what could be the problem?
> ```
># NA -- Error -- /global/u1/h/houhun/cori/mercury/src/na/na_ofi.c:2905
># na_ofi_handle_send_event(): ignore the send_event as the op is completed.
># NA -- Error -- /global/u1/h/houhun/cori/mercury/src/na/na_ofi.c:2963
># na_ofi_handle_recv_event(): ignore the recv_event as noi_tag 0x2 mismatch with cq_event->tag: 0x1.
># NA -- Error -- /global/u1/h/houhun/cori/mercury/src/na/na_ofi.c:2905
># na_ofi_handle_send_event(): ignore the send_event as the op is completed.
># NA -- Error -- /global/u1/h/houhun/cori/mercury/src/na/na_ofi.c:2963
># na_ofi_handle_recv_event(): ignore the recv_event as noi_tag 0x2 mismatch with cq_event->tag: 0x1.
> ```

**Comment by liuxuezhao** [comment]
just curious before that err msg, did the testing program did any cancel/abort operation? for example by calling HG_Cancel or NA_Cancel, or did any server dead?

The err msg shows the OP is completed before but still got completion event, so it just ignore it. Any other bad behaviour happen besides the msg?

**Comment by soumagne** [comment]
I don't think Tang is doing that. @houjun Tang, could you describe what you were doing in that case?

**Comment by houjun** [comment]
I launched multiple server processes with MPI, then multiple clients start to send RPCs to the servers, no cancel/abort operation is involved, the messages are printed out right after the clients are started. There's no problem if only one server is started with many clients.

**Comment by soumagne** [comment]
@houjun Hi Tang, could you please try again with latest master?

**Comment by houjun** [comment]
I think this issue is resolved, I'm no longer seeing the errors when running my code.

**Comment by soumagne** [comment]
OK thanks for letting me know I assume commit 9a327def457dfa4349d4615ff866330ddbd92d3b fixed it.
