### ISSUE TITLE
Add configurable option to disable max number of posted requests

### ISSUE THREAD

**Issue by soumagne** [mercury-hpc/mercury#175]
Requested by @zhengqmark
When processes control the number of requests that are sent, there is no need for the server to limit the number of requests that get pre-posted. Currently the max number of requests is set to 256, there should be an option to remove that limit.

**Comment by zhengqmark** [comment]
There can be a minor compilation issue when setting -DMERCURY_ENABLE_POST_LIMIT:BOOL=OFF. I was using gcc 4.9, which is pretty old by now.

/users/qingzhen/src/zhengqmark/deltafs-umbrella/bu/mercury-prefix/src/mercury/src/mercury.c: In function ‘HG_Context_create_id’:
/users/qingzhen/src/zhengqmark/deltafs-umbrella/bu/mercury-prefix/src/mercury/src/mercury.c:798:24: error: expected expression before ‘>’ token
         (HG_POST_LIMIT > 0) ? HG_POST_LIMIT : HG_POST_LIMIT_DEFAULT;
                        ^
src/CMakeFiles/mercury.dir/build.make:86: recipe for target 'src/CMakeFiles/mercury.dir/mercury.c.o' failed
make[5]: *** [src/CMakeFiles/mercury.dir/mercury.c.o] Error 1
CMakeFiles/Makefile2:93: recipe for target 'src/CMakeFiles/mercury.dir/all' failed
make[4]: *** [src/CMakeFiles/mercury.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/mercury.dir/build.make:113: recipe for target 'mercury-prefix/src/mercury-stamp/mercury-build' failed
make[2]: *** [mercury-prefix/src/mercury-stamp/mercury-build] Error 2
CMakeFiles/Makefile2:175: recipe for target 'CMakeFiles/mercury.dir/all' failed
make[1]: *** [CMakeFiles/mercury.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
