### ISSUE TITLE
Installation: git failing to find submodule KWsys

### ISSUE THREAD

**Issue by mdorier** [mercury-hpc/mercury#178]
When trying to clone Mercury, git fails to find the KWsys submodule:

Cloning into 'Testing/driver/kwsys'...
fatal: repository 'https://public.kitware.com/KWSys.git/' not found
Clone of 'http://public.kitware.com/KWSys.git' into submodule path 'Testing/driver/kwsys' failed

The repository seems not to exist anymore, the new repo seems to be:
https://gitlab.kitware.com/utils/kwsys

Matthieu

**Comment by soumagne** [comment]
It may have been a server issue on their end, it seems to be working fine for now but I have updated the URL as it seems the gitlab repo is now the official one.
