### ISSUE TITLE
NA OFI: psm2 provider disables naming server

### ISSUE THREAD

**Issue by soumagne** [mercury-hpc/mercury#181]
From the `fi_psm2` manpage:

       FI_PSM2_NAME_SERVER  :  The  psm2  provider  has a simple built-in name
       server that can be used to resolve an IP address or host  name  into  a
       transport address needed by the fi_av_insert call.  The main purpose of
       this name server is to allow  simple  client-server  type  applications
       (such  as those in fabtests) to be written purely with libfabric, with‐
       out using any out-of-band communication mechanism.  For  such  applica‐
       tions, the server would run first, and the client would call fi_getinfo
       with the node parameter set to the IP  address  or  host  name  of  the
       server.   The  resulting  fi_info  structure  would  have the transport
       address of the server in the dest_addr field.

       The name server won't work properly if there are  more  than  one  pro‐
       cesses from the same job (i.e.  with the same UUID) running on the same
       node and acting as servers.  For such scenario  it  is  recommended  to
       have  each  process getting local transport address with fi_getname and
       exchanging the addresses with out-of-band mechanism.

       The name server is on by default.  It can be turned off by setting  the
       variable  to 0.  This may save a small amount of resource since a sepa‐
       rate thread is created when the name server is on.

It seems that we are hitting that issue within the NA OFI plugin when it is used in conjunction with MPI and it requires a manual export of the ` FI_PSM2_NAME_SERVER` environment variable. The manpage explicitly mentions though that this will not work if there are multiple processes on the same node acting as servers and that `fi_getname` should be used instead. We should look to see whether this is something that can be done in the OFI plugin.

**Comment by soumagne** [comment]
@liuxuezhao Hi Xuezhao, can you please take a look at that issue when you have some time? Thanks!

**Comment by liuxuezhao** [comment]
Yeah, this is a known issue. " this will not work if there are multiple processes on the same node acting as servers" I think it is because the name service use a default port number, so the multiple processes on same node will conflict with that port.

To resolve this, I think it would need an HG/NA API to export the output of server side fi_getname, and user needs to explicitly exchange that result by out-of-band communication (by MPI or socket or anything else) and provide it to addr_lookup().

**Comment by carns** [comment]
Can the output of fi_getname() be put into the output HG_Addr_to_string() if HG_Addr_to_string() is called on the "self" address for a process?  If so, then we already have API to get addressing information for an out-of-band addressing system to use.

The https://xgitlab.cels.anl.gov/sds/ssg library already operates like this, at least in some bootstrapping methods.  It queries the local address on each process and then exchanges it to peers.  @shanedsnyder can confirm.

**Comment by soumagne** [comment]
Right @liuxuezhao I'm not sure I understood your comment, that's what we already do with na_ofi_addr_to_string, currently though we do not use fi_getname for PSM2 though to generate the uri, see line 1529 of na_ofi.c. I can't remember the reason now...

**Comment by soumagne** [comment]
@carns See https://github.com/mercury-hpc/mercury/blob/master/src/na/na_ofi.c#L1489 I feel like this is the problem that we have, we just generate the URI using IP+port but in that case the URI really needs to be retrieved from fi_getname() as we already do for the other transports (tcp/verbs). Looks like we have the same problem with gni so I should also look at that one.

**Comment by liuxuezhao** [comment]
"Can the output of fi_getname() be put into the output HG_Addr_to_string() if HG_Addr_to_string() is called on the "self" address for a process?"
Right. One problem is fi_getname will return a RAW address, and commonly the HG_Addr_to_string() returned is a string with IP and Port. For PSM2, if client using the IP+Port for address resolution then will need the name server mentioned above.
The RAW addr also can be translated to a "string", it looks like we want to support two kinds of format one is IP+Port and another is RAW format...

"currently though we do not use fi_getname for PSM2 to generate the uri, see line 1529 of na_ofi.c. I can't remember the reason now..."
In the code the fi_getname is called for all providers, and we want to use fi_av_straddr() to convert it to a string with IP+Port format. But fi_av_straddr() is not supported for PSM2 (maybe also for GNI) so we did not call fi_av_straddr() for PSM2/GNI.

**Comment by soumagne** [comment]
Hmm... I think we can just use the raw format in that case. The string returned from HG_Addr_to_string does not have to respect the IP+port format. The only thing is that then when it gets passed to HG_Addr_lookup() we need to be able to use that string.

**Comment by soumagne** [comment]
But yes I think you're right, maybe we could have a similar option that selects the format of the string that gets generated, either IP format or RAW format.

**Comment by carns** [comment]
RAW sounds perfectly fine (Mercury can just put a psm2:// prefix on it before passing it out), with the caveat that that will mainly just work for cases where we don't need the service to specify it's address ahead of time.

That's a good first step, and maybe all that we need for a lot of use cases anyway...

**Comment by liuxuezhao** [comment]
Agreed with all you comments, thanks.

But need to do some testing/experiments, one problem is currently the OFI plugin addr hash table is identified by IP/Port but might be able to refine.
