### ISSUE TITLE
Mchecksum: turn SSE4_2 on when available

### ISSUE THREAD

**Issue by soumagne** [mercury-hpc/mercury#182]
It is currently manually enabled by the user, it would be good to be able to auto-detect it.

**Comment by carns** [comment]
It looks like there is a cmake example here:

https://github.com/VcDevel/Vc/blob/master/cmake/FindSSE.cmake

... with the caveat that something like this (that checks /proc) won't necessarily work correctly when cross-compiling.  It's probably still helpful though; if cmake produces the wrong results someone can always override the checksum mode manually.

**Comment by soumagne** [comment]
thanks, yeah it would be nice if there were some more standard way of checking for it... but yes that can be a better solution than not having it at all :)
