### ISSUE TITLE
NA OFI: inconsistent na_info_string address format requirements for HG_Init() across NA plugins

### ISSUE THREAD

**Issue by carns** [mercury-hpc/mercury#183]
The CCI, BMI, and na+sm plugins allow the na_info_string argument to HG_Init() to be simply "proto://" if na_listen is 0 (i.e., the process is purely a client).  OFI, in contrast, requires that clients provide a fully specified "proto://hostname:port" or "proto://iface:port" na_info_string to HG_Init() even though they will not be listening for RPCs.

The former is more convenient.  Maybe the na_ofi code can make an educated guess at the full address string for clients if the caller does not provide it, or at least print a verbose error message explaining what the caller needs to do?

**Comment by soumagne** [comment]
OK yes I agree I think it would be good to be consistent. Let me see what I can do.

**Comment by soumagne** [comment]
I just pushed a fix for it, it should be fine with tcp now at least, I'm going to do some more testing with gni

**Comment by soumagne** [comment]
You can now simply pass ofi+tcp in the init string when you initialize either in client or server (i.e. listening or not). If you are listening it will pick up a port automatically.

**Comment by carns** [comment]
Awesome, thanks Jerome.
