### ISSUE TITLE
addr_to_string() doesn't include na plugin prefix

### ISSUE THREAD

**Issue by carns** [mercury-hpc/mercury#186]
This is a problem when you compile in support for two NA plugins that can handle the same program, e.g. cci+verbs and ofi+verbs.  If you start a server with an ofi+verbs address, it will resolve it's own address to a string that looks like this:

```
verbs://fi_sockaddr_in://172.23.100.132:46326
```

If you give that address to a client, however, it will try to give that address to the cci plugin (because cci takes precedent over ofi if both support verbs) and a segfault occurs.

I think this would work Ok if the addr_to_string prepended the ofi+ prefix so that other processes could tell which na plugin is expected for communication.

**Comment by soumagne** [comment]
Ah I see yes OK I will fix that.

**Comment by soumagne** [comment]
Oh but wait, do you mean you give that address to the HG_Init() call? How can it use the cci plugin if you do HG_Init() with ofi+verbs for example?

**Comment by carns** [comment]
Ah, right, so to be more specific: when I give the client an address like verbs://fi_sockaddr_in://172.23.100.132:46326, my client program is stripping off everything after the // and using that as the argument to HG_Init(), then using the whole address in the addr_lookup call.

Basically I'm trying to get the client to select it's HG_Init() argument automatically based on the server address that it is instructed to connect to.

This problem might not exist if it were (for example) an MPI program where every process uses an identical, pre-selected HG_Init() argument.  I can't test that right now though do to some apparent bad interaction between MPI and fi_verbs...

**Comment by soumagne** [comment]
OK yes that makes sense then I can fix NA to automatically include the plugin name then.

**Comment by soumagne** [comment]
Should be fine now, plugins will just need to be careful to always add the protocol first when generating the string.

**Comment by carns** [comment]
Confirmed the fix works- thanks @soumagne !
