### ISSUE TITLE
mechanism to set configuration options at run time (or init time)

### ISSUE THREAD

**Issue by carns** [mercury-hpc/mercury#187]
I would like to have an API mechanism to set optional configuration parameters at run time.

Example: a hint telling Mercury to optimize for speed in cases where the caller does not intend to use timeouts in Progress() or Trigger(), by skipping retrieving the na-specific file descriptor that would be used for epoll().  Simply instantiating this fd (even if not used) appears to have significant overhead on some transports.

An option like this would have to be set before the na plugin is activated, but I don't see a way in the API to do this.  Should we have some sort of hint/param/info API in Mercury, or some way to pass string options to HG_Init() for this sort of thing?

I can prototype what I want and have it triggered by environment variable, but that's kind of error-prone for long-term use.

**Comment by soumagne** [comment]
When working with @liuxuezhao on adding scalable endpoints, we draft the following new API call (see https://github.com/mercury-hpc/mercury/blob/topic_ofi/src/mercury.h):
```C
/**
 * Initialize the Mercury layer with options providing by init info.
 * Must be finalized with HG_Finalize().
 *
 * \param na_info_string [IN]   host address with port number (e.g.,
 *                              "tcp://localhost:3344" or
 *                              "bmi+tcp://localhost:3344")
 * \param na_listen [IN]        listen for incoming connections
 * \param init_info [IN]        Optional HG init info, can be NULL if not
 *                              needed.
 *
 * \return Pointer to HG class or NULL in case of failure
 */
HG_EXPORT hg_class_t *
HG_Init_opt(
        const char *na_info_string,
        hg_bool_t na_listen,
        const struct hg_init_info *init_info
);
```
We could use that also for activating that mode as well?

**Comment by carns** [comment]
That works for me.  My only comment (if there is a well-defined struct with named fields in it for the options instead of a string format) is that we need make sure it's clear how to set some options but not others.  For example, I might not understand the ramifications of that max_contexts parameter when I want to set an option that controls polling policy :)

**Comment by soumagne** [comment]
Hmm yes we'll need to be careful about that. If max_contexts is 0, it would be simply ignored but other options should behave similarly so that ideally you can just memset the struct to 0 or we could have some initializer macro.
