### ISSUE TITLE
ship with boost preprocessor headers

### ISSUE THREAD

**Issue by roblatham00** [mercury-hpc/mercury#211]
requiring boost inflates mercrury's dependencies (consider the case of creating a docker image).   If mercury shipped with and installed the boost preprocessor headers, we could skip the boost dependency and save hundreds of megabytes.  boost is also lengthy to compile, so being able to skip the boost dependency would speed up `spack install mercury`, too. 

The boost tool 'bcp' can package up the headers for it: for example

    bcp preprocessor --boost=/sandbox/robl/boost_1_66_0/ src/boost

**Comment by carns** [comment]
FYI, here's what I see if I try this on an Ubuntu machine:

```
pcarns@carns-x1:~$ mkdir /tmp/test
pcarns@carns-x1:~$ bcp preprocessor --boost=/usr/include /tmp/test |wc
    269     807   14463
pcarns@carns-x1:~$ du -sh /tmp/test
3.3M	/tmp/test
```

It's 3 MB of stuff.  It is purely .hpp files, though (starting with boost/preprocessor.hpp as the umbrella header, which is included by mercury_macros.h).

**Comment by soumagne** [comment]
I was also looking at it on my fedora machine but somehow they do not ship boost with the bcp command...

**Comment by carns** [comment]
On Ubuntu I had to install libboost-tools-dev to get the bcp command.

**Comment by soumagne** [comment]
Yeah somehow they don't seem to ship that in fedora, I'm not really sure why... maybe because it requires the sources?

**Comment by soumagne** [comment]
I was comparing the headers with what gets shipped in the distro and it's exactly the same so I don't think we even need to use the bcp tool...

**Comment by brianjmurrell** [comment]
Is this bundling really appropriate for a "production" level release?  How would this co-operate on a system that otherwise needs boost-devel installed, say, to build other software that needs boost?

Is there a _cmake_ switch to disable this bundling of boost?

**Comment by soumagne** [comment]
Right `MERCURY_USE_SYSTEM_BOOST` is the way to go.
