### ISSUE TITLE
Target id not sent to or retrieved correctly by server

### ISSUE THREAD

**Issue by dorier** [mercury-hpc/mercury#214]
This bug appeared very recently. The scenario is the following:

A client creates a handle for an RPC and sets its target id to something other than 0. It then forwards to the server. On the server, HG_Get_info returns a pointer to an info struct where target_id is 0, not the target id specified by the client.

**Comment by soumagne** [comment]
The target ID (renamed context_id) now reflects the ID of either the target or origin context of the handle.
