### ISSUE TITLE
Submodule url refuse connection

### ISSUE THREAD

**Issue by ael-code** [mercury-hpc/mercury#220]
The following submodule has a url that doesn't work anymore.
https://github.com/mercury-hpc/mercury/blob/master/.gitmodules#L3

In particular it refuses connection. Thus it is not possible to run:
```
git clone --recurse-submodules https://github.com/mercury-hpc/mercury.git
```

**Comment by carns** [comment]
I've had trouble with that submodule occasionally too, it seems like gitlab.kitware.com isn't completely reliable.  Maybe that repo should be cloned into https://github.com/mercury-hpc/ so the submodule can reference that?

**Comment by soumagne** [comment]
Hmm you are not the first one who mentions that. I do not have any issue with it right now but it seems that it happens from time to time. Probably the best solution is to update the url to point to a fork that we will keep updated on GitHub.

**Comment by soumagne** [comment]
@carns ha your message appeared as I posted mine :) yes I agree we should do that.
