### ISSUE TITLE
cmake: exported target is broken 

### ISSUE THREAD

**Issue by ael-code** [mercury-hpc/mercury#224]
I'm experiencing an issue with an old cmake version (`2.8.12.2`).

The installation of exported target generates the `${INSTALL_PREFIX}/share/mercury/mercury-targets.cmake`. Turns out that the `na` target has a wrong  `INTERFACE_INCLUDE_DIRECTORIES` property. Looking at the generated `mercury-targets.cmake` code:
```
# Create imported target na
add_library(na SHARED IMPORTED)

set_target_properties(na PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "mercury_util;/opt/adafs/build_deps/lib/libbmi.so;/opt/adafs/build_deps/lib/libcci.so;/opt/adafs/build_deps/lib/libfabric.so"
)
```
 The problem is that ${_IMPORT_PREFIX} is empty. Thus the `na` target ends up having `/include` as include directory, that is obviously wrong.

Probably this is related to this issue that I've found https://cmake.org/Bug/view.php?id=15258

**Comment by soumagne** [comment]
Thanks for reporting the problem, it should be fine now.
