### ISSUE TITLE
NA OFI: outdated documentation about psm2 addresses 

### ISSUE THREAD

**Issue by ael-code** [mercury-hpc/mercury#230]
I'm on f7f6955f140426b2a7c9e26dc35f8c8e1654d86a

Even if it isn't mentioned in the docs, to look-up psm2 endpoints we can use the native psm2 address in the form of `ofi+psm2://fi_addr_psmx2://40302:101`

If the psm2 name server is active we can also use the following format:
 - `ofi+psm2://<ip>`
 - `ofi+psm2://<hostname>`

The problem is that if we add also a port as stated by the current documentation, the address resolution won't work. For instance using `ofi+psm2://<hostname>:<port>` it won't work.

The documentation says almost nothing about this situation, and it took me a while to understand all those things.

**Comment by soumagne** [comment]
Yes that was added recently and the documentation has not been updated, I think ideally we'd also want it to succeed in that case. We need to take a pass at making the OFI plugin initialization less restrictive.

**Comment by soumagne** [comment]
Documentation will need to be updated after #246 is merged to reflect NA OFI addressing changes

**Comment by ael-code** [comment]
This issue has been closed but no information have been provided about how has been fixed. Any commit reference?

**Comment by soumagne** [comment]
The table on http://mercury-hpc.github.io/documentation/#available-plugins has been updated to reflect the current behavior.
