### ISSUE TITLE
new release plans?

### ISSUE THREAD

**Issue by brianjmurrell** [mercury-hpc/mercury#238]
I notice quite some time and a large number of commits since the last release.

Are there any plans to make a release soon?

**Comment by soumagne** [comment]
Yes I am planning to make a new release that includes the libfabric plugin around September.

**Comment by brianjmurrell** [comment]
Did we get there or still waiting?  Any new ETA?

**Comment by soumagne** [comment]
Still waiting for now, I would like to get the remaining pull requests in first. Will update the ETA on https://github.com/mercury-hpc/mercury/milestone/8

**Comment by soumagne** [comment]
mercury-1.0.0rc1 tarball was created

**Comment by brianjmurrell** [comment]
Awesome!
