### ISSUE TITLE
minor ofi error handling bug

### ISSUE THREAD

**Issue by chuckcranor** [mercury-hpc/mercury#241]
I get the following error:
```
# NA -- Error -- mercury-prefix/src/mercury/src/na/na_ofi.c:1647
 # na_ofi_endpoint_open(): na_ofi_basic_ep_open failed, ret: -28.
```
this "-28" value shouldn't be possible since it's a na_return enum

na_ofi_basic_ep_open() is failing because fi_enable() is returning an error  => there is a mercury error handling bug here around line 1741 that explains the -28 value:
```
    /* Enable the endpoint for communication, and commits the bind operations */
    ret = fi_enable(na_ofi_endpoint->noe_ep);
    if (rc != 0) {
        NA_LOG_ERROR("fi_enable failed, rc: %d(%s).", rc, fi_strerror(-rc));
        ret = NA_PROTOCOL_ERROR;
        goto out;
    }
```
that "ret = fi_enable()" should be "rc = fi_enable(...)" ... this is where the unexpected -28 comes from.

-28 decodes to the OFI version of ENOSPC (No space left on device).

**Comment by chuckcranor** [comment]
This is related to MPICH_GNI_NDREG_ENTRIES environment variable not being set.
Phil suggested we might look for this condition and print a more helpful error message.

**Comment by carns** [comment]
Just to clarify @chuckcranor  comment for posterity, as of September 2018, Mercury will fail to initialize if it is set to use the GNI provider when Cray MPICH is already activated unless the MPICH_GNI_NDREG_ENTRIES environment variable is set.  This is a very likely configuration when running on a Cray system.  We'll therefore look for this environment variable up front and display an error message if it isn't set.

**Comment by soumagne** [comment]
I should have actually commented here :) One thing though is that I'm wondering now if we could not remove the use of udreg and just use the internal registration cache. This way we would not even need to show that error message anymore about the NDREG_ENTRIES stuff (unless I'm missing or forgetting something)

**Comment by soumagne** [comment]
I think that before Howard thought there was a bug in the libfabric registration cache (and I believe he had fixed it) so for safety we started using the udreg cache. Again I may have forgotten something so we should test again without udreg and see if it works.

**Comment by soumagne** [comment]
I'll just merge your pull request for now and I'll get back to that later.
