### ISSUE TITLE
NA SM: documentation is misleading

### ISSUE THREAD

**Issue by ael-code** [mercury-hpc/mercury#250]
#229 has been removed from the release plan of the version `1.0.0` of mercury. Thus I think the documentation should be modified before the next big release.

In particular:

> Plugin is stable and shows good performance

After first disconnection NA_SM plugin is using 100% of a CPU. I wouldn't say good performance :)

> Supports dynamic client connection and disconnection.

Yeap, but is actually allocating a socket for each connection and never de-allocating them on disconnection. I would mention that

> Low CPU consumption (e.g., idles without busy spinning or using threads).

This is true only before the first client disconnection. Again... After that will consume 100% of a core.

**Comment by soumagne** [comment]
Alright :) I'll see about implementing a short-term fix

**Comment by ael-code** [comment]
> Alright :) I'll see about implementing a short-term fix

thanks

**Comment by soumagne** [comment]
That should be fixed now but let me know if you see any wrong behavior. Thanks!
