### ISSUE TITLE
NA SM: bmi+tcp plugin doesn't support SM routing 

### ISSUE THREAD

**Issue by ael-code** [mercury-hpc/mercury#252]
**Describe the bug**
Is not possible to use the bmi+tcp plugin with the shared memory routing enabled `auto_sm = HG_TRUE`

**To Reproduce**
Just run the server test with shared memory routing `-m` and the bmi+tcp plugin:
```
hg_test_server -m -c bmi -p tcp
```
And you'll get the following error:
```
# Using info string: bmi+tcp://localhost:22222
# HG -- Error -- /mercury/src/mercury_core.c:3665
 # HG_Core_context_create_id(): Auto SM mode not supported with selected plugin
# HG Util -- Error -- /mercury/src/util/mercury_poll.c:402
 # hg_poll_remove(): Could not find fd in poll_set
# HG -- Error -- /mercury/src/mercury_core.c:3835
 # HG_Core_context_destroy(): Could not remove NA poll descriptor from poll set
# HG -- Error -- /mercury/src/mercury.c:1295
 # HG_Context_create_id(): Could not create context for ID 0
# HG -- Error -- /mercury/src/mercury_core.c:3968
 # HG_Core_context_set_data(): NULL HG core context
```

**Comment by soumagne** [comment]
Right and it won't be supported unless we either force busy polling (which could be enabled) or spawn a thread internally (which we don't do). Is there any reason for you to use bmi+tcp instead of ofi+tcp?

**Comment by ael-code** [comment]
> Right and it won't be supported unless we either force busy polling (which could be enabled) or spawn a thread interofi/verbs is not thread-safe and requires a global lock to be internally acquired when accessing the libfabric API, hence should be considered as experimental.
onally (which we don't do). Is there any reason for you to use bmi+tcp instead of ofi+tcp?

Ok, I'll try with `ofi+tcp`.
Is this the same as `ofi+sockets`?

I've got a little bit confused by the documentation because in the OFI plugin section it first says:
```
The plugin currently supports sockets/psm2/verbs/gni providers
```
Then it talks about the `tcp/sockets provider` and then it uses the combination `ofi/sockets`.
And in the table there is not `sockets` among the supported protocol for OFI but only `ofi+tcp`.

Probably a more consistent naming will help stupid developer like me :) 

In any case, is there any place in the documentation that says which plugin support the 'auto shared memory routing' feature?

**Comment by soumagne** [comment]
OK I'm working on the documentation now, hopefully will clarify that. That feature was introduced after version 0.9.0 and the documentation was just simply not updated.
