### ISSUE TITLE
NA OFI: ofi+sockets listen on any interface

### ISSUE THREAD

**Issue by ael-code** [mercury-hpc/mercury#253]
**Is your feature request related to a problem? Please describe.**
I couldn't make the server listen an all the interfaces using `ofi+sockets`

**Describe the solution you'd like**
I would like to be able to use something on the line of `INADDR_ANY` or `0.0.0.0` when specifying the domain.

Is this possible with the current internal architecture of mercury?

**Comment by soumagne** [comment]
It is currently not supported by the libfabric "sockets" providers but I expect it to be supported in the near future when we switch to the new tcp provider from libfabric that uses rxm (which will deprecate the sockets provider, that should be transparent on your end though).
On another note, we also had an issue to listen to a specific address/port and that will be resolved when #246 is merged.

**Comment by soumagne** [comment]
Also if that is more convenient to you, you can pass the interface name instead of the hostname or IP address.

**Comment by soumagne** [comment]
This is supported after recent changes in the OFI plugin.
