### ISSUE TITLE
MERCURY_USE_SM_ROUTING is silently ignored if LibUUID is missing

### ISSUE THREAD

**Issue by ael-code** [mercury-hpc/mercury#258]
**Describe the bug**
If LibUUID is not found by cmake the `MERCURY_USE_SM_ROUTING` is silently ignored.

**To Reproduce**
Uninstall LibUUID and pass `-DMERCURY_USE_SM_ROUTING:BOOL=ON` to CMake

**Expected behavior**
I would expect that CMake would throw an error explaining that SM auto routing cannot be supported without LibUUID.

**Comment by soumagne** [comment]
Thanks for reporting that, I will take a look.
