### ISSUE TITLE
Improve error reporting from HG_Progress()

### ISSUE THREAD

**Issue by alberto-miranda** [mercury-hpc/mercury#261]
**Is your feature request related to a problem? Please describe.**
We are working on a C++11 asynchronous engine leveraging Mercury for communication and while testing we found that, if the server is not running, the `HG_Addr_lookup()` function succeeds (at least with the BMI plugin, mind you) and the `HG_Progress()` function reports the following error:

```
# NA -- Error -- /projects/mercury/src/na/na_bmi.c:2012
 # na_bmi_progress_expected(): BMI_testcontext failed, error code set
# NA -- Error -- /var/projects/mercury/src/na/na_bmi.c:1878
 # na_bmi_progress(): Could not make expected progress
# HG -- Error -- /var/projects/mercury/src/mercury_core.c:2979
 # hg_core_progress_na(): Could not make NA Progress
# HG -- Error -- /var/projects/mercury/src/mercury_core.c:4948
 # HG_Core_progress(): Could not make progress
```
This in itself is not a problem, but we would like to be able to report this error to the clients that are still waiting for the affected RPCs. As it is right now, we have not found any way to associate the error reported with the `HG_Forward()` call that provoked it, which means that our clients end up waiting indefinitely.

**Describe the solution you'd like**
Ideally, we would like a way for `HG_Progress()` to return/propagate some kind of context from which the user data previously passed to `HG_Forward()` could be retrieved. This way, we could easily propagate the error to our RPC's execution context, and report the error to the user.  

**Describe alternatives you've considered**
Another option would be to provide the `hg_handle_t` associated to the request that failed. This way we could associate some execution context with `HG_Set_data()` and retrieve it with `HG_Get_data()`.

**Comment by soumagne** [comment]
@alberto-miranda thanks for the report. What you would need to do in that case is set a timeout for waiting clients and when that timeout is reached have the clients call `HG_Cancel()`. Once the `HG_Forward()` operation has been successfully canceled you'll be able to retrieve the data that you passed to your `HG_Forward()` call. Have a look at that page: http://mercury-hpc.github.io/documentation/2016/07/26/cancellation.html it will give you an example of how to proceed. Please let me know if anything is not clear.

**Comment by alberto-miranda** [comment]
After digging through the code of the NA layer code I found out that the handles affected could be retrieved (for some plugins) via the `na_XXX_op_id` structures. Nevertheless, I also noticed that the `ofi+socket` plugin does not produce an error if the server is no longer there, and the client waits indefinitely for something to happen, which means that (though theoretically possible) returning the affected handles to the upper layers might not be very useful, and I’m also not sure whether there would be thread-safety issues with this approach.

Since we are using `futures` to keep track of pending results, and they support a `wait_for(timeout)` operation, we could reasonably keep track of how much time has passed since a request was posted through `HG_Forward()` and wait for the remaining timeout if any. It would not be as precise as using the time when the request actually started progressing, but with a large enough timeout it would work for most reasonable situations. Then, if I understood the documentation correctly, we could cancel the request with `HG_Cancel()` and use the `completion_callback` to repost the RPC (or fail, or whatever) if `cbi->ret == HG_CANCELLED`. Is that correct?

Just for the sake of conversation, this is how we currently do progress which is very similar to how Mercury's `example_rpc_engine.c` does it:

```cpp
    /**
     * Dedicated thread that drives Mercury progress
     */
    void
    progress_thread() {

        assert(m_hg_class);
        assert(m_hg_context);

        hg_return ret;
        unsigned int actual_count;

        while(!m_shutdown) {
            do {
                ret = HG_Trigger(m_hg_context,
                                 0,
                                 1,
                                 &actual_count);
            } while((ret == HG_SUCCESS) &&
                    (actual_count != 0) &&
                    !m_shutdown);

            if(!m_shutdown) {
                ret = HG_Progress(m_hg_context, 100);

                if(ret != HG_SUCCESS && ret != HG_TIMEOUT) {
                    WARNING("Unexpected return code {} from HG_Progress: {}",
                            ret, HG_Error_to_string(ret));
                }
            }
        }
    }
```

We are currently using a dedicated thread, but ​I was wondering whether it would be problematic to have other idle threads call `HG_Progress()` when they don't have work to do. I seem to recall another issue where it was mentioned that this could lead to a deadlock?

With regards to Thallium, I'm aware of it but we cannot currently use it in our project because it enforces a synchronous progress model through Margo and an asynchronous model fits our needs better. Also, it depends on Argobots which might have some issues with our internal pool of threads (we should probably have used Margo from the beginning, but we were not aware of it when the project began). Finally, due to project constraints, we need stick to C++11-compliant code, and the last time I tried I could not compile Thallium with `--std=c++11`. Nevertheless, thanks for the suggestion.

**Comment by soumagne** [comment]
That's correct, you just need to check for the `HG_CANCELED` state in the completion callback and take the appropriate action.
Regarding the extra threads, it depends on your use case, just keep in mind that having extra threads sharing the same context will add extra locking and potentially degrade performance, also because they are sharing the same endpoint underneath. No deadlock though. The only way to keep up with performance is to use scalable endpoints and have one context per progress thread. I will post something soon about it on that page: http://mercury-hpc.github.io/documentation/2018/10/22/progress-modes.html
For Thallium, OK yes that makes sense, just wanted to make sure you were aware of it.

**Comment by alberto-miranda** [comment]
Cool, thanks. I'll keep an eye out for it.
