### ISSUE TITLE
sse detection failures on Cray when compiling on front-end node

### ISSUE THREAD

**Issue by chuckcranor** [mercury-hpc/mercury#271]
Normally when compiling software for Cray compute nodes on a front-end node, you are supposed to set -DCMAKE_SYSTEM_NAME=CrayLinuxEnvironment.  Doing this with mercury currently causes the following failure:
<pre>
> cmake -DCMAKE_SYSTEM_NAME=CrayLinuxEnvironment ../mercury
-- The C compiler identification is Cray 8.7
-- Cray Linux Environment 6.0.UP06
-- Cray Programming Environment 2.5.15 C
-- Check for working C compiler: /opt/cray/pe/craype/2.5.15/bin/cc
-- Check for working C compiler: /opt/cray/pe/craype/2.5.15/bin/cc -- works
-- Detecting C compiler ABI info
..
-- Looking for process_vm_readv
-- Looking for process_vm_readv - found
CMake Error: TRY_RUN() invoked in cross-compiling mode, please set the following cache variables appropriately:
   MCHECKSUM_CAN_RUN_SSE4_2 (advanced)
   MCHECKSUM_CAN_RUN_SSE4_2__TRYRUN_OUTPUT (advanced)
For details see /home/ccranor/src/deltafs-umbrella/b/mercury-prefix/src/mb/TryRunResults.cmake
</pre>

The reason it is complaining is because we are calling try_run() on the front-end node to run a program that tests for a hardware feature on the compute nodes.  This test needs to run on a compute node in order to get a valid result (e.g. you want to send it through mpirun or srun).

Supposed you omit -DCMAKE_SYSTEM_NAME=CrayLinuxEnvironment.    The try_run() will attempt to compile CheckSSE42.c and run it on the front-end node.  This program has the following semantic: if you run it on hardware that supports SSE then it exit(1)'s.  Otherwise it exit(0)'s.

Now suppose you are on a non-KNL Cray front-end, using the intel compiler (module PrgEnv-intel), and planning to run on a KNL node (so you have module "craype-mic-knl" loaded too).  If you compile a program with this compiler and run it, it will fail with the following error (and exit(1)):
<pre>

Please verify that both the operating system and the processor support Intel(R) AVX512F, ADX, AVX512ER, AVX512PF and AVX512CD instructions.

</pre>

If you try and build mercury in this case, it will call try_run() to build and run CheckSSE42.c.  When it runs that program, it will fail with the above error message and exit 1.   Note here that it is exiting with 1 because of the error, not because it detected SSE42, but the mercury config cannot tell the difference and treats the exit 1 as "SSE42 is present" ...

To see this, put some message() calls after the try_run() in mercury/src/mchecksum/src/CMakeLists.txt:
<pre>
try_run(MCHECKSUM_CAN_RUN_SSE4_2 MCHECKSUM_CAN_COMPILE_SSE4_2
  ${CMAKE_BINARY_DIR} ${MCHECKSUM_CMAKE_DIR}/CheckSSE42.c
  OUTPUT_VARIABLE CHECK_SSE4_2_OUTPUT
)
message("CANRUN: ${MCHECKSUM_CAN_RUN_SSE4_2}")
message("CANCOM: ${MCHECKSUM_CAN_COMPILE_SSE4_2}")
message("OUTVAR: ${CHECK_SSE4_2_OUTPUT}")
</pre>

and you'll see the error:
<pre>
-- Looking for process_vm_readv - found
CANRUN: 1
CANCOM: TRUE
OUTVAR: Change Dir: /home/ccranor/src/deltafs-umbrella/b/mercury-prefix/src/mb/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_9c53a/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_9c53a.dir/build.make CMakeFiles/cmTC_9c53a.dir/build
gmake[1]: Entering directory '/gpfs/mira-home/ccranor/src/deltafs-umbrella/b/mercury-prefix/src/mb/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_9c53a.dir/CheckSSE42.c.o
/opt/cray/pe/craype/2.5.15/bin/cc    -o CMakeFiles/cmTC_9c53a.dir/CheckSSE42.c.o   -c /home/ccranor/src/deltafs-umbrella/b/mercury-prefix/src/mercury/src/mchecksum/CMake/CheckSSE42.c
Linking C executable cmTC_9c53a
/home/ccranor/tmp/cth/bin/cmake -E cmake_link_script CMakeFiles/cmTC_9c53a.dir/link.txt --verbose=1
/opt/cray/pe/craype/2.5.15/bin/cc      -dynamic CMakeFiles/cmTC_9c53a.dir/CheckSSE42.c.o  -o cmTC_9c53a 
gmake[1]: Leaving directory '/gpfs/mira-home/ccranor/src/deltafs-umbrella/b/mercury-prefix/src/mb/CMakeFiles/CMakeTmp'

Please verify that both the operating system and the processor support Intel(R) AVX512F, ADX, AVX512ER, AVX512PF and AVX512CD instructions.

-- Using SSE 4.2 instruction set.
-- Configuring done
> 
</pre>

I think it would be better to avoid try_run() if possible.

**Comment by soumagne** [comment]
Hmm ok thanks for letting me know about it, I'm happy not to use try_run(). Any suggestion for detecting SSE then? On the other hand the try_run() command output currently just sets the default option for using SSE42 or not and users can still overwrite that result by setting the option manually. One thing we should definitely do though is check for any errors. Is there any harm if that try_run() command fails otherwise?

**Comment by chuckcranor** [comment]
What I would do is have the mchecksum compilation contain multiple checksum implementations (e.g. plain, SSE, ...) and then have it do the cpuid check at run time as part of a one-time init function and use the result of that to set function pointers to the most efficient implementation available.   If we needed a way to get rid of this layer of indirection, I'd add an compile-time option to lock it down directly to a specific implementation (prob making use of the preprocessor or inline functions to let the compiler optimize the call).   With that you would not need try_run() and you'd just need to worry about the compiler supporting the necessary asm() or intrinsic ops needed to access the special hardware instructions you want to use...

**Comment by soumagne** [comment]
@chuckcranor this was fixed in f9cf4d252d6bd2357e0cf649e35ace05c5b3f0c2
