### ISSUE TITLE
NA OFI: Add support for new tcp provider

### ISSUE THREAD

**Issue by ael-code** [mercury-hpc/mercury#274]
With latest Libfabric `v1.7.0` a new [TCP provider](https://github.com/ofiwg/libfabric/blob/master/NEWS.md#tcp) has been introduced. According to the official man pages it should provide better performance with respect to the old sockets provider and in the long term it should replace it completely.

At the moment mercury doesn't expose this provider. Actually if you try to use `ofi+tcp`, internally mercury will use the old `ofi+sockets` provider.

**Comment by soumagne** [comment]
That's correct, we haven't enabled it as we need to evaluate which features are supported or missing but I do expect it will replace the sockets provider.

**Comment by soumagne** [comment]
Merged in #282
