### ISSUE TITLE
mercury protocol delimiter match the one used by libfabric

### ISSUE THREAD

**Issue by ael-code** [mercury-hpc/mercury#277]
Mercury use `;` as protocol delimiter that is exactly the same used by libfabric. This cause parsing issue in the [`hg_core_addr_lookup`](https://github.com/mercury-hpc/mercury/blob/0de22781cd08931416aba8050c5a6647c23abcb9/src/mercury_core.c#L1318) function. In particular when the `ofi+verbs` provider is used the self address will look like this:
`ofi+verbs;ofi_rxm://10.1.0.111:41816`

The `hg_core_addr_lookup` would split the address using the delimiter `;` and will threat the first part `ofi+verbs` as UID and the second part  `ofi_rxm://10.1.0.111:41816` as remote address.

In order to reproduce the issue, the AUTO_SM feature needs to be enabled at compile time and the ofi+verbs provider needs to be used.

**Comment by ael-code** [comment]
In order to fix the issue I've simply changed the [`HG_CORE_ADDR_DELIMITER`](https://github.com/mercury-hpc/mercury/blob/0de22781cd08931416aba8050c5a6647c23abcb9/src/mercury_core.c#L50) to `#` and everything works flawlessly.

**Comment by soumagne** [comment]
OK yes that makes sense, I need to double check but I guess we could just use `#` :) I don't think OFI uses that one.
