### ISSUE TITLE
NA OFI: ofi+tcp ignore specified port silently

### ISSUE THREAD

**Issue by ael-code** [mercury-hpc/mercury#278]
when using ofi+tcp provider, if an invalid port number is specified in the margo init address, it will be ignored silently and the server will bind to a random port.

Example:
using `ofi+tcp://172.17.0.2:65536` self address will be `ofi+sockets://172.17.0.2:41589`

**Comment by soumagne** [comment]
Hmm that should be supported. I specifically remember having fixed that in the past.

**Comment by soumagne** [comment]
I see I had misread your description and thought you meant you could not select which port to listen to, which is supported. Unless we add some code in the OFI plugin that checks for that, any port number that you give is currently passed as a hint to OFI that will try to use it, i.e. the "silently ignored" is currently not controlled by mercury. Which behavior are you expecting? an error or a warning? At the minimum we should document it I think.
