### ISSUE TITLE
Failure with OFI/PSM2

### ISSUE THREAD

**Issue by adrianjhpc** [mercury-hpc/mercury#289]
When running the test server/client with PSM2 and OFI I get a failure of the server once the client has started communicating. I'm using:
```
mpirun -n 1  ./hg_test_server --comm ofi --protocol psm2
```
To start the test server and:
```
mpirun -n 2 ./hg_test_perf --comm ofi --protocol psm2 
```
To start the test client.

I am using Intel MPI, and have done the following:
```
export PSM2_MULTI_EP=1
```
(without the above the variable set the server will not start). Both the client and server are running on the same node for this test.

If I run the client it connects to the server and sends some data but the server then fails with errors like this:

```
# Using info string: ofi+psm2://localhost:22222
# Waiting for client...
# NA -- Error -- /home/nx02/nx02/modules/central-package-location/mercury/1.0.1/source/mercury-1.0.1/src/na/na_ofi.c:2623
 # na_ofi_op_id_valid(): invalid magic number for na_ofi_op_id.
# NA -- Error -- /home/nx02/nx02/modules/central-package-location/mercury/1.0.1/source/mercury-1.0.1/src/na/na_ofi.c:2793
 # na_ofi_cq_process_event(): Bad na_ofi_op_id, ignoring event.
# NA -- Error -- /home/nx02/nx02/modules/central-package-location/mercury/1.0.1/source/mercury-1.0.1/src/na/na_ofi.c:4783
 # na_ofi_progress(): Could not process event
# HG -- Error -- /home/nx02/nx02/modules/central-package-location/mercury/1.0.1/source/mercury-1.0.1/src/mercury_core.c:3019
 # hg_core_progress_na_cb(): Could not make progress on NA
# HG Util -- Error -- /home/nx02/nx02/modules/central-package-location/mercury/1.0.1/source/mercury-1.0.1/src/util/mercury_poll.c:469
 # hg_poll_wait(): poll cb failed
# HG -- Error -- /home/nx02/nx02/modules/central-package-location/mercury/1.0.1/source/mercury-1.0.1/src/mercury_core.c:3260
 # hg_core_progress_poll(): hg_poll_wait() failed
# HG -- Error -- /home/nx02/nx02/modules/central-package-location/mercury/1.0.1/source/mercury-1.0.1/src/mercury_core.c:4826
 # HG_Core_progress(): Could not make progress
# NA -- Error -- /home/nx02/nx02/modules/central-package-location/mercury/1.0.1/source/mercury-1.0.1/src/na/na_ofi.c:4824
 # na_ofi_cancel(): fi_cancel unexpected recv failed, rc: -11(Resource temporarily unavailable).
```

Any ideas what's going wrong?

**Comment by soumagne** [comment]
Hmm weird. Which version of libfabric are you using? Also which version of psm2? Thanks

**Comment by adrianjhpc** [comment]
Libfabric 1.7.1. The PSM2 version is hard to get, but I think it's 11.2.23.

**Comment by carns** [comment]
I don't know what's wrong in @adrianjhpc 's test case, but I can share some more psm2 data that I see in my testing.  With the following environment I can run simple communication patterns just fine, but they crash when there is concurrency involved (concurrent RPCs in flight and or concurrent bulk transfers in flight):

```
Currently Loaded Modules:
  1) intel/17.0.4-74uvhji
  2) intel-mpi/2017.3-dfphq6k
  3) intel-mkl/2017.3.196-v7uuj6z
  4) StdEnv
  5) gcc_new/7.3.0
  6) numactl/2.0.11-tggunqu
  7) boost/1.65.1-pka2h73
  8) cmake/3.12.2-4zllpyo
  9) intel-mpi-2017.3-gcc-7.3.0-ybq56zs
 10) ssg-0.2-gcc-7.3.0-pqlvzx5
 11) libuuid-1.0.3-gcc-7.3.0-yxfmy3i
 12) argobots-develop-gcc-7.3.0-ew4pfjk
 13) bzip2-1.0.6-gcc-7.3.0-kvx54d7
 14) zlib-1.2.7-gcc-7.3.0-ssvvb5b
 15) boost-1.70.0-gcc-7.3.0-jys7glr
 16) numactl-2.0.11-gcc-7.3.0-hh4u6jh
 17) opa-psm2-11.2.68-gcc-7.3.0-mmtzuv5
 18) libfabric-1.7.1-gcc-7.3.0-prrqr3y
 19) mercury-1.0.1-gcc-7.3.0-rnssp6r
 20) margo-0.4.7-gcc-7.3.0-c457v2g
 21) pmdk-1.6-gcc-7.3.0-zewfuol
 22) autoconf-2.69-gcc-7.3.0-tqdcehr
 23) openssl-1.0.2k-gcc-7.3.0-hnslhci
 24) pkg-config-0.29.2-gcc-7.3.0-v6hpcqy
 25) abt-io-0.3.1-gcc-7.3.0-s43o46u
 26) thallium-0.3.4-gcc-7.3.0-jnecx3t
 27) remi-0.2.1-gcc-7.3.0-xxxieqa
 28) bake-0.3.2-gcc-7.3.0-ggckevc
```

I'm also using the PSM2_MULTI_EP environment variable.

**Comment by soumagne** [comment]
@carns are you really using that version of psm2? I get build failures with spack using that version and had to use 11.2.23...

**Comment by carns** [comment]
Yeah, the upstream spack package doesn't work right for newer versions of psm2.  I've got a PR open, but until it lands I'm using my fork/branch for these tests:

https://github.com/spack/spack/pull/11658

**Comment by carns** [comment]
Sorry for the piecemeal updates, but @adrianjhpc I wanted to let you know that I have a combination that is (mostly) working now.

If I use that spack branch to get a newer opa-psm2, and then also install the current origin/master of libfabric (libfabric@develop if you are using spack), then I can complete a sweep across 24 different concurrent benchmark test parameters with all but 1 of them completing successfully.

I don't know why 1 of 24 crashed, but this is a much better outcome than I have seen before with a recent psm2 library.  

libfabric@develop is similar to what will be in the upcoming libfabric 1.8 release, I believe.

**Comment by adrianjhpc** [comment]
Thanks @carns I'll try the latest libfabric and see if I get can get stuff working.

**Comment by adrianjhpc** [comment]
@carns do you get your newer opa-psm2 from https://github.com/intel/opa-psm2?

**Comment by adrianjhpc** [comment]
Using PSM2 11.2.77 and libfabric 1.8.0 I still get:

```
# Using info string: ofi+psm2://localhost:22222
# Starting server with 8 threads...
# Waiting for client...
^[[A# NA -- Error -- /home/nx02/nx02/modules/central-package-location/mercury/latest/source/mercury/src/na/na_ofi.c:2623
 # na_ofi_op_id_valid(): invalid magic number for na_ofi_op_id.
# NA -- Error -- /home/nx02/nx02/modules/central-package-location/mercury/latest/source/mercury/src/na/na_ofi.c:2793
 # na_ofi_cq_process_event(): Bad na_ofi_op_id, ignoring event.
# NA -- Error -- /home/nx02/nx02/modules/central-package-location/mercury/latest/source/mercury/src/na/na_ofi.c:4783
 # na_ofi_progress(): Could not process event
# HG -- Error -- /home/nx02/nx02/modules/central-package-location/mercury/latest/source/mercury/src/mercury_core.c:3019
 # hg_core_progress_na_cb(): Could not make progress on NA
# HG Util -- Error -- /home/nx02/nx02/modules/central-package-location/mercury/latest/source/mercury/src/util/mercury_poll.c:583
 # hg_poll_wait(): poll cb failed
# HG -- Error -- /home/nx02/nx02/modules/central-package-location/mercury/latest/source/mercury/src/mercury_core.c:3260
 # hg_core_progress_poll(): hg_poll_wait() failed
# HG -- Error -- /home/nx02/nx02/modules/central-package-location/mercury/latest/source/mercury/src/mercury_core.c:4830
 # HG_Core_progress(): Could not make progress
```
from `hg_test_server` when `hg_test_perf` gets to 
```
###############################################################################
# Bulk test (rma)
###############################################################################
# Reading Bulk Data (16.000000 MB) with 2 client(s) -- loop 1 time(s)
# Warming up...
```

**Comment by carns** [comment]
@shanesnyder can comment more, but I think we are still getting some (relatively rare but still present) problems with the latest psm2 and libfabric also, but they don't align with what you are seeing @adrianjhpc .

By any  chance have you tried tests with the 10.x versions of psm2?  Like maybe 10.3-37?

**Comment by adrianjhpc** [comment]
I've tried with 10.3.46 and get the same behaviour.

**Comment by soumagne** [comment]
@adrianjhpc I've tried to replicate your failure but don't see any problem (@carns using bebop with 10.2.78). You mention that you are running on the same node though, do you see the same issue when using separate nodes? I'm actually not sure how to replicate that using a single node with slurm to run this test.

**Comment by adrianjhpc** [comment]
I was bypassing slurm for these tests to rule out that it was something to do with slurm that was the issue, so I was just sshing directly into a node with two sessions to run the client and server. I will try on two separate nodes as well.

**Comment by adrianjhpc** [comment]
Running on two separate nodes (using ssh, not slurm) I get the same issues. @soumagne in your tests were you running on omnipath? If so, can you let me know the specific versions of psm2, libfabric, and mercury, so I can replicate your environment?

**Comment by soumagne** [comment]
hmm I've tried with mercury master, libfabric 1.8.0 and psm2 11.2.78. Does this also happen with one single client process? Since you are using multiple processes for client, can you also make sure that you have MERCURY_ENABLE_PARALLEL_TESTING turned ON in CMake? It just adds a few barriers to make sure the server does not get killed before the clients have completed.

**Comment by adrianjhpc** [comment]
I've tried with a single client process and with MERCURY_ENABLE_PARALLEL_TESTING on but no difference.

Intel tell me the PSM2 only is currently tested up to libfabric 1.6.2, so I'll try with that version and see if it makes a difference.

**Comment by adrianjhpc** [comment]
Is it possible for me to get an account on BeBop to check the relative configurations to see why our install is failing when the reference  one doesn't? Alternatively I can give people access to our cluster so they can check our installs.

**Comment by carns** [comment]
Hi @adrianjhpc I'll shoot you an email and see what we can work out.
