### ISSUE TITLE
warning: inline function ‘decode_PVFS_sys_layout’ declared but never defined

### ISSUE THREAD

**Issue by tonyhutter** [mercury-hpc/mercury#296]
**Describe the bug**
Using gcc (GCC) 9.1.1 20190503 (Red Hat 9.1.1-1) on Fedora 30, I get the following warnings when building `master`:
```
./include/pvfs2-types.h:230:13: warning: inline function ‘decode_PVFS_sys_layout’ declared but never defined
  230 | inline void decode_PVFS_sys_layout(char **pptr, struct PVFS_sys_layout_s *x);
      |             ^~~~~~~~~~~~~~~~~~~~~~
./include/pvfs2-types.h:229:13: warning: inline function ‘encode_PVFS_sys_layout’ declared but never defined
  229 | inline void encode_PVFS_sys_layout(char **pptr, const struct PVFS_sys_layout_s *x);
      |             ^~~~~~~~~~~~~~~~~~~~~~
./include/pvfs2-types.h:78:13: warning: inline function ‘decode_PVFS_BMI_addr_t’ declared but never defined
   78 | inline void decode_PVFS_BMI_addr_t(char **pptr, PVFS_BMI_addr_t *x);
      |             ^~~~~~~~~~~~~~~~~~~~~~
./include/pvfs2-types.h:77:12: warning: inline function ‘encode_PVFS_BMI_addr_t_size_check’ declared but never defined
   77 | inline int encode_PVFS_BMI_addr_t_size_check(const PVFS_BMI_addr_t *x);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/pvfs2-types.h:76:13: warning: inline function ‘encode_PVFS_BMI_addr_t’ declared but never defined
   76 | inline void encode_PVFS_BMI_addr_t(char **pptr, const PVFS_BMI_addr_t *x);
```

**To Reproduce**
```
./prepare && ./configure --enable-shared --enable-bmi-only && make
```
**Expected behavior**
No warnings

**Screenshots**

**Platform (please complete the following information):**
gcc (GCC) 9.1.1 20190503 (Red Hat 9.1.1-1) on Fedora 30

**Additional context**

**Comment by carns** [comment]
Hi @tonyhutter , coincidentally we just migrated BMI to Argonne's gitlab instance (https://xgitlab.cels.anl.gov/sds/bmi) because the old git server that we were using is being retired.  As a side effect, that means that it has it's own issue tracker now, though :)

Would you mind reposting your issue there and we will close this one?  This is technically a BMI problem and not a Mercury problem.

If you have an idea of how to solve it you are welcome to open a PR as well.  Contributions to the BMI code base do not require a CLA.

**Comment by tonyhutter** [comment]
Unfortunately, I don't have Argonne gitlab account, so I can't repost the issue.

**Comment by carns** [comment]
You can sign up for one (anyone can sign up for an external account on that system).  I can post the issue there for you if you would rather, but if you do it then you will see update notifications.

**Comment by tonyhutter** [comment]
Yea, If you don't mind, could you please post it?  I'd rather not create yet another account...

**Comment by carns** [comment]
Sure thing!

https://xgitlab.cels.anl.gov/sds/bmi/issues/1
