### ISSUE TITLE
is it intentional to use all three digits of the version for the library SONAMEs?

### ISSUE THREAD

**Issue by brianjmurrell** [mercury-hpc/mercury#298]
**Describe the bug**
```
$ objdump -p  /usr/lib64/libmercury.so.1.0.1 | grep SONAME
  SONAME               libmercury.so.1.0.1
```
AFAIU, typically shared libraries break backward compatible ABI only on major versions (or vice-versa, update the major version on non-backward compatible ABI breakages), update the minor on forward compatible ABI changes (so that the major version is still compatible with existing behaviours) and no ABI break on bugfix update.

But mercury is including all three in it's SONAME, indicating that every single mercury version released is non-backward compatible with it's predecessor.

Is this intentional?

**To Reproduce**
N/A

**Expected behavior**
SONAME should just be major version: libmercury.so.1

**Screenshots**
N/A

**Platform (please complete the following information):**
 - System description: EL7.6
 - Compiler version: e.g. gcc 4.8

**Additional context**
None

**Comment by soumagne** [comment]
OK I would need to review that. I'm not entirely sure that we want to simply change it that way. If I look at my system for example I have for zlib:
```bash
/usr/lib64/libz.so (installed with zlib-devel package)
/usr/lib64/libz.so.1 (installed with zlib package)
/usr/lib64/libz.so.1.2.11 (installed with zlib package)
```
So it just sounds like it should just be an extra symbolic link that would need to be created?

**Comment by soumagne** [comment]
And yes the SONAME would need to be fixed too.

**Comment by brianjmurrell** [comment]
@soumagne Indeed.  I would bet that if you use `objdump -p` on that `/usr/lib64/libz.so.1.2.11` and look at the SONAME value, it would say `libz.so.1`.  That's the library name.version that things linked to `libz` look for, and why the symlink from `/usr/lib64/libz.so.1` to `/usr/lib64/libz.so.1.2.11` is created.

This ends up meaning that libz can be upgraded to any 1.x.x version and anything linked to it will continue to work with such upgrades all the way up to 1.999*.9999*.

Much thanks for looking into this.

**Comment by brianjmurrell** [comment]
As an aside, only because I have been looking through some commits, I notice in 9b1e7fa9d3456504fb7a236cb06c4192283fbbeb that several previously exported functions were changed to static inline and no longer exported.

This is exactly the kind of change that warrants bumping the version from major 1 to major 2 as things built with 1.x.x that expect those functions to be available will break after that patch.

**Comment by brianjmurrell** [comment]
I just re-read your comments in my e-mail copy and wanted to clarify...

> So it just sounds like it should just be an extra symbolic link that would need to be created?

This is not something that your build/install process needs to do beyond just setting the SONAME of the library.  The linker is what should create the symlinks.

**Comment by soumagne** [comment]
@brianjmurrell this is now fixed in master. Of course this won't be of any use until we create a new release.

**Comment by soumagne** [comment]
And I will also need to update mchecksum to reflect that change.

**Comment by brianjmurrell** [comment]
> @brianjmurrell this is now fixed in master. Of course this won't be of any use until we create a new release.

That's awesome!  Thanks.

I did leave a [comment](https://github.com/mercury-hpc/mercury/commit/a73eb8ce1f7caaac5e6c55123785fe952710cecc#r34690110) on the commit if you cared to take a look.

**Comment by soumagne** [comment]
@brianjmurrell and the version number has been updated to 2.0.0a1
