### ISSUE TITLE
Cannot compile with cmake 3.15.1

### ISSUE THREAD

**Issue by mdorier** [mercury-hpc/mercury#299]
I'm trying to install mercury using spack. When spack uses cmake version 3.15.1 (the most recent one at the time of posting this issue), the build Mercury build process fails with the following error:

```
CMake Error at src/util/CMakeLists.txt:38 (CHECK_SYMBOL_EXISTS):
     Unknown CMake command "CHECK_SYMBOL_EXISTS".
```

The build process works fine when using cmake 3.14.4.

**Comment by soumagne** [comment]
@mdorier this is fixed now.
