### ISSUE TITLE
Default Spack install fails

### ISSUE THREAD

**Issue by CamStan** [mercury-hpc/mercury#301]
**Describe the bug**
Fixing #299 with [this commit](https://github.com/mercury-hpc/mercury/commit/05831f8db8c2916628d03cb0caee339134a2997c) seems to have caused a side effect when installing with Spack.

**To Reproduce**
The default version of Mercury in the Spack package is 1.0.1. So if installing everything fresh with Spack, `spack install mercury`, you get `cmake@3.15.1` and `mercury@1.0.1` which then reproduces the issue in #299:

```
[prompt]$ spack install mercury
==> Installing mercury
⋮
==> Executing phase: 'cmake'
⋮
  >> 30    CMake Error at src/util/CMakeLists.txt:38 (CHECK_SYMBOL_EXISTS):
     31      Unknown CMake command "CHECK_SYMBOL_EXISTS".
     32
     33
     34    -- Configuring incomplete, errors occurred!
```

After troubleshooting and finding the issue, was able to use workarounds of either using the master branch:
```
spack install mercury@master
```
or an older version of cmake
```
spack install mercury ^cmake@3.14.5
```

**Expected behavior**
One of two things,

1. `spack install mercury` will default to a working combination (newer version, master branch, or older cmake)
2. `spack install mercury@1.0.1 ^cmake@3.15.1` will provide a proper error

**Platform (please complete the following information):**
 - System description
 - Compiler version: [gcc 4.9.3]
 - Plugin and protocol used [ofi, sm]
 - Dependency version [spack defaults: libfabric 1.8.0, bmi, boost 1.70.0]

**Potential solutions**

Add a `conflicts` or `depends_on` to the Mercury Spack package so users know what is wrong if trying to install with the latest cmake and default version.

1. Add a `conflicts`:
```
conflicts('^cmake@3.15.0:', when='@:1.0.1')
```
results in:
```
[prompt]$ spack spec mercury@1.0.1 ^cmake@3.15.1
Input spec
--------------------------------
mercury

Concretized
--------------------------------
==> Error: Conflicts in concretized spec
⋮
1. "^cmake@3.15.0:" conflicts with "mercury@:1.0.1"
```

or

2. Add a `depends_on`:
```
depends_on(cmake@:3.14.999', when='@:1.0.1', type='build')
```
results in:
```
[prompt]$ spack spec mercury@1.0.1 ^cmake@3.15.1
Input spec
--------------------------------
mercury

Concretized
--------------------------------
==> Error: An unsatisfiable version constraint has been detected for spec:
⋮
mercury requires cmake version 2.8.12.2:3.14.999, but spec asked for 3.15.1
```

Other combinations (i.e., `spack install mercury@master`) succeed.

**Comment by soumagne** [comment]
Right I don't think the fix for #299 causes any side effects. It's just that the Spack package needs to be updated so that cmake >= 3.15 does not get used with mercury 1.0.1. I'll fix the spack package to reflect that.

**Comment by CamStan** [comment]
True. Probably not the best choice of wording on my part.

Thank you for the response and for looking into it.

**Comment by chuckatkins** [comment]
With https://github.com/spack/spack/pull/12504 merged in upstream spack this should be fixed now.
