### ISSUE TITLE
Accepting 0-sized bulk handles and 0-sized bulk transfers

### ISSUE THREAD

**Issue by mdorier** [mercury-hpc/mercury#304]
Right now `HG_Bulk_create` and `HG_Bulk_transfer` will fail when being given 0 segments, or 0-sized segments, or 0-sizes transfers. I think there really is no reason for that: it forces the upper application to check that the segments it wants to expose or transfer have a non-zero size.

Ideally, it should be allowed to create a bulk handle exposing no memory at all and it should be allowed to do a bulk transfer of 0 bytes (which would be a no-op) without error.

**Comment by soumagne** [comment]
Fixed in #399
