### ISSUE TITLE
"tcp_rxm" added to string addresses, making HG_Addr_lookup fail

### ISSUE THREAD

**Issue by mdorier** [mercury-hpc/mercury#310]
When initializing a Mercury server with "ofi+tcp" then using `HG_Addr_self` and converting the address to a string, I'm getting something like `ofi+tcp;ofi_rxm://10.0.2.15:42363`, which I cannot use on clients to call `HG_Addr_lookup` (call fails). I need to remove the `;ofi_rxm` from the address for `HG_Addr_lookup` to work.

Could Mercury remove this part of the address?

**Comment by carns** [comment]
Just to add some extra information: verbs uses ofi_rxm as well, but presumably doesn't have this problem?  I haven't looked to see if they are handling address strings differently, though.

**Comment by soumagne** [comment]
Ugh, what? :) I definitely test it that way and it works fine? Why do you need to remove the ofi_rxm part?

**Comment by mdorier** [comment]
This is what I'm getting:

```
# NA -- Error -- /tmp/mdorier/spack-stage/mercury-master-7bbslxovmxwec4veom2zifkt5fgkc4fn/spack-src/src/na/na_ofi.c:1112
 # na_ofi_str_to_sin(): Malformed FI_ADDR_STR: tcp

# NA -- Error -- /tmp/mdorier/spack-stage/mercury-master-7bbslxovmxwec4veom2zifkt5fgkc4fn/spack-src/src/na/na_ofi.c:3679
 # na_ofi_addr_lookup(): Could not convert string to address
# HG -- Error -- /tmp/mdorier/spack-stage/mercury-master-7bbslxovmxwec4veom2zifkt5fgkc4fn/spack-src/src/mercury_core.c:1398
 # hg_core_addr_lookup(): Could not start lookup for address ofi+tcp
# HG -- Error -- /tmp/mdorier/spack-stage/mercury-master-7bbslxovmxwec4veom2zifkt5fgkc4fn/spack-src/src/mercury_core.c:4280
 # HG_Core_addr_lookup(): Could not lookup address
Function returned HG_NA_ERROR
```

**Comment by carns** [comment]
Ah, is it possible @mdorier that the ';' character is getting parsed by the shell (was it passed on a command line?)?

```console
[pcarns@carns-x1 examples (master)]$ ./margo-example-client ofi+tcp;ofi_rxm://192.168.11.215:36683
# NA -- Error -- /tmp/pcarns/spack-stage/mercury-master-v3t2ee5o4whdj3r6fa7yeb5ikbwmfom3/spack-src/src/na/na_ofi.c:1112
 # na_ofi_str_to_sin(): Malformed FI_ADDR_STR: tcp
...
```

```console
[pcarns@carns-x1 examples (master)]$ ./margo-example-server ofi+tcp;ofi_rxm://
# accepting RPCs on address "ofi+tcp;ofi_rxm://192.168.11.215:36683"
Got RPC request with input_val: 0
Got RPC request with input_val: 1
Got RPC request with input_val: 2
Got RPC request with input_val: 3
Got RPC request to shutdown
```

The second example just has quotation marks around the string.  This wouldn't happen if the string were passed programmatically (as in SSG for example) but could happen on the command line.

FWIW ';' is a pretty terrible delimiter, but libfabric chose this so we are kind of stuck.

**Comment by mdorier** [comment]
Yeas, that was actually the problem. I'm closing the issue. Thanks!
