### ISSUE TITLE
Mercury’s error model for disappearing exposed buffers?

### ISSUE THREAD

**Issue by alberto-miranda** [mercury-hpc/mercury#312]
I was wondering what Mercury’s error model is when a client buffer that has been exposed for RDMA disappears because the client process crashed? What happens at the server that is doing a remote push/pull operation? It hopefully won’t crash but, is a sensible error reported?

**Comment by soumagne** [comment]
Yes you will receive an error during bulk transfer, both OFI and SM would most likely return a no such file or directory type of error. It is true though that currently we do not differentiate that type of error and we just throw a generic NA_PROTOCOL_ERROR. I think we should add a few more error reporting codes and include that one.
