### ISSUE TITLE
Is it possible to "pause progress" in Mercury?

### ISSUE THREAD

**Issue by alberto-miranda** [mercury-hpc/mercury#320]
Hi,

We are currently having some issues with Mercury and `fork()`/`clone()` system calls due to fds and the internal `epoll()` set in the parent being duplicated in the new process. Since we are not calling `exec()` immediately after `fork()` we end up with an inconsistent state of the copied Mercury library in the child process. 

A possible solution to our problem that we are currently exploring is to intercept the `fork()`/`clone()` system calls and, when one does arrive, "pause" Mercury from making progress, execute the actual `fork()` and resume Mercury progress in the parent and reinitialize the library in the child. I was wondering whether stopping our progress thread would be enough to suspend Mercury progress completely or if there's further progress made in the NA layer.

**Comment by soumagne** [comment]
Hmm I think I would need to think about all the implications of doing that. If you pause the progress thread, would you still be making HG calls? It is currently still possible for some of those calls to call into non-blocking progress.

**Comment by alberto-miranda** [comment]
Our current progress thread does the following (feel free to point out any issues with it):

```C++
    void
    progress_thread() {

        assert(m_hg_class);
        assert(m_hg_context);

        hg_return ret;
        unsigned int actual_count;

        while(!m_shutdown) {
            do {
                ret = ::HG_Trigger(m_hg_context,
                                 0,
                                 1,
                                 &actual_count);

                DEBUG4("HG_Trigger(context={}, timeout={}, "
                              "max_count={}, actual_count={}) = {}", 
                              fmt::ptr(m_hg_context), 0, 1, actual_count, 
                              ::HG_Error_to_string(ret));

            } while((ret == HG_SUCCESS) &&
                    (actual_count != 0) &&
                    !m_shutdown);

            if(!m_shutdown) {
                ret = ::HG_Progress(m_hg_context, 100);

                DEBUG4("HG_Progress(context={}, timeout={}) = {}", 
                              fmt::ptr(m_hg_context), 100, 
                              ::HG_Error_to_string(ret));

                if(ret != HG_SUCCESS && ret != HG_TIMEOUT) {
                    FATAL("Unexpected return code {} from HG_Progress: "
                                 "{}", ret, ::HG_Error_to_string(ret));
                }
            }
        }
    }
```
It would certainly be possible to stop the progress thread in a similar way as it's done with `m_shutdown`, which would stop the thread from calling `HG_Progress()`. From my (admittedly limited) understanding the Mercury code, this function eventually calls `epoll_wait()`, which tells the kernel to deliver any pending requests to the calling process, so stopping the parent process from doing this would leave us in a "safe state" where requests are processed by the kernel, but not yet delivered to any process, which would allow us to `fork()` the process safely. 

I'm not sure, however, about what happens at the `NA` layer: are there further calls to `epoll_wait()` (or `accept()` or any similar calls) done at the `NA` layer? If that were the case, it might not be sufficient to stop our progress thread to `fork()` the process safely.

**Comment by soumagne** [comment]
If you stop the progress thread, there are no other epoll_wait() calls so you should be safe on this side. I'm wondering if you will not encounter other issues though when using libfabric etc.
