### ISSUE TITLE
ofi+ prefix now required on address strings

### ISSUE THREAD

**Issue by carns** [mercury-hpc/mercury#322]
**Describe the bug**

As recently as a couple of months ago we were able to run benchmarks using "psm2://" as the address prefix on OmniPath machines.  Now, however, we get the following error:

```
# NA -- Error -- /tmp/carns/spack-stage/spack-stage-mercury-master-tfebuvecudqiz3epvfjpngqj2chrhsat/spack-src/src/na/na.c:281
 # NA_Initialize_opt(): Specified class name does not support requested protocol
# HG -- Error -- /tmp/carns/spack-stage/spack-stage-mercury-master-tfebuvecudqiz3epvfjpngqj2chrhsat/spack-src/src/mercury_core.c:1130
 # hg_core_init(): Could not initialize NA class
# HG -- Error -- /tmp/carns/spack-stage/spack-stage-mercury-master-tfebuvecudqiz3epvfjpngqj2chrhsat/spack-src/src/mercury_core.c:3628
 # HG_Core_init_opt(): Cannot initialize HG core layer
# HG -- Error -- /tmp/carns/spack-stage/spack-stage-mercury-master-tfebuvecudqiz3epvfjpngqj2chrhsat/spack-src/src/mercury.c:1093
 # HG_Init_opt(): Could not create HG core class
```

Things work correctly if we use "ofi+psm2://" instead.

This also seems to have happened with verbs as well (requires ofi+verbs were it would previously work with just verbs).  Tagging @roblatham00 because I think he has observed the verbs issue.

**Comment by soumagne** [comment]
I'm having a look at it right now. It works with sm but tcp/sockets do not work either.

**Comment by soumagne** [comment]
@carns fixed

**Comment by carns** [comment]
confirmed on verbs, psm2, and gni transports.  Thanks @soumagne !
