### ISSUE TITLE
HG_Addr_to_string() fails on address with na_sm components

### ISSUE THREAD

**Issue by alberto-miranda** [mercury-hpc/mercury#324]
**Describe the bug**
`HG_Addr_to_string()` fails with the following message if a client calls it on a `hg_addr_t` address returned from a previous `HG_Addr_lookup()` call to a server address with `auto_sm` enabled:

```
# NA -- Error -- /home/amiranda/projects/test/deps/mercury/src/na/na_ofi.c:3780
 # na_ofi_addr_to_string(): Addr to string is not available on unexpected addresses
# HG -- Error -- /home/amiranda/var/projects/test/deps/mercury/src/mercury_core.c:1676
 # hg_core_addr_to_string(): Could not convert address to string
# HG -- Error -- /home/amiranda/var/projects/test/deps/mercury/src/mercury_core.c:4426
 # HG_Core_addr_to_string(): Could not convert address to string
Failed to create string from self address: HG_NA_ERROR
```

**Detailed description**

Starting a server with `HG_Init_opts()` and the `auto_sm` option set produces a valid address string similar to `uid://37455477-21d3-4833-9865-24a6c395c40e;na+sm://9527/0;ofi+sockets://192.168.0.105:50000`. If a client running on the same machine tries to look it up by using `HG_Addr_lookup()` on the previous address, the call succeeds but attempting to produce a string from the returned address with `HG_Addr_to_string()` fails.

From what I've seen, `HG_Addr_to_string()` attempts to interpret the provided `hg_addr_t` as a `fi_addr_t` address and fails to do so since in reality the returned address seems to correspond to a `struct na_sm_addr` address. I believe (but I'm not entirely sure) that one or both of the `hg_core_addr_lookup_cb()` callbacks in `mercury.c` and `mercury_core.c` should realize that the returned address has a shared memory "part" and should act accordingly rather than simply initializing the corresponding `na_addr` to the returned address. 

The bug (assuming it's not expected behavior) can be reproduced by compiling and running [this server](https://gist.github.com/alberto-miranda/34991440fb86c539b003eccbf6f25e66) and [this client](https://gist.github.com/alberto-miranda/235f08887ff219ac5e5a9d7ece1efdd1).

**Other considerations**
Mercury was built with `-DNA_USE_OFI:BOOL=ON`,  `-DMERCURY_USE_SM_ROUTING:BOOL=ON`, and `-DMERCURY_USE_SELF_FORWARD:BOOL=ON`.

**Comment by soumagne** [comment]
@alberto-miranda could you please let me know which version of mercury you are using? I will have a look at that address to string issue with sm.

**Comment by alberto-miranda** [comment]
We detected the error with commit 9906f25b6f9c52079d57006f199b3ea47960c435 (which for now is the latest that we have fully tested with our code), and I also managed to reproduce it using the sample code I provided you both with 9906f25b6f9c52079d57006f199b3ea47960c435 and with the latest HEAD 9889a0d0ba8854c1a0c2bd186a01fac4f57edada.
