### ISSUE TITLE
Potential segv if memory allocation fails.

### ISSUE THREAD

**Issue by ashleypittman** [mercury-hpc/mercury#328]
I'm trying to work out what happens if this memory allocation fails, it looks from reading the code like mercury would segv in hg_proc_buf_memcpy() but I'm trying to test this now.

What would you expect to happen here, would it be enough to simply check here and return an error code or do the extra values need to be unpacked from the input buffer?

Edit - github seems to have failed me, this ticket should reference this line of code where a string is received as part of a RPC.
https://github.com/mercury-hpc/mercury/blob/master/src/proc_extra/mercury_proc_string.h#L184

**Comment by soumagne** [comment]
Yes it should return an error there. Will get that in as part of a bunch of fixes that I'm about to create a PR for. Thanks!

**Comment by soumagne** [comment]
Fixed in 68a82c82f8084f9cc695c775db7c82268f832c26
