### ISSUE TITLE
problem of building test

### ISSUE THREAD

**Issue by wangzhezhe** [mercury-hpc/mercury#339]
There is following error when I build the test:

[ 39%] Linking C executable ../bin/hg_test_read_bw
/usr/bin/ld: ../bin/libmercury.a(mercury.c.o):(.data+0x0): multiple definition of `hg_log_mask'; ../bin/libmercury_hl.a(mercury_hl.c.o):(.data+0x0): first defined here
/usr/bin/ld: ../bin/libna.a(na.c.o):(.data+0x0): multiple definition of `na_log_mask'; ../bin/libna_test.a(na_test.c.o):(.data+0x0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [Testing/CMakeFiles/hg_test_read_bw.dir/build.make:93: bin/hg_test_read_bw] Error 1
make[1]: *** [CMakeFiles/Makefile2:1259: Testing/CMakeFiles/hg_test_read_bw.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

The gcc version is 8.3.0 and the git commit is c2c262813811c3ede2 (master branch)

Thanks!

**Comment by soumagne** [comment]
@wangzhezhe is this resolved with current master branch or do you still see that issue?

**Comment by wangzhezhe** [comment]
@soumagne Thanks for your help, I could try it
