### ISSUE TITLE
NA: unspecified handling of multi-homed/INADDRY_ANY ip addresses

### ISSUE THREAD

**Issue by chuckcranor** [mercury-hpc/mercury#342]
Mercury has multiple NAs that use IP addressing.  The handling of hosts with multi-homed/INADDR_ANY IPs has not been been fully specified and has resulted in non-uniform behavior across NAs.

We discussed this on the Mochi mailing list and came up with the following:

1. users are allowed to bind mercury servers to either a specific IP address on a host, or they are allowed to bind to INADDR_ANY using "0.0.0.0" or an empty host spec.  In the later case, binding to INADDR_ANY should show up in "netstat -a -n" as being bound to 0.0.0.0.   NAs must not bind to a specific IP address if the user requested INADDR_ANY.

1. users can either bind to a specific port number, or they can bind to port 0.  If the user binds to port 0, then that means that the kernel is allowed to assign the port number to a currently unused port.  If you bind to port 0, the way to determine the port number assigned by the kernel is to get your "self" address and convert it to a string.   If a user requests a specific non-zero port number and that port number is already in use, then the NA should cause the mercury init function to return an error.

1. when users bind to INADDR_ANY, mercury will allow inbound RPC requests on any active IP interface, as expected.   If a user using INADDR_ANY wants to advertise the address they are listening on, they can use HG_Addr_self() and HG_Addr_to_string() to generate their address string.  But in the case of INADDR_ANY, we can advertise our address as "0.0.0.0"!   In this case, we need to pick one of the system's valid IP addresses and use that instead of "0.0.0.0" (we considered returning a list of all IP addresses, but that seems too complicated).   How do we pick the IP address for HG_Addr_to_string()?   By default, we let Mercury pick a random local IP address (e.g. could be the first address returned by getifaddrs(3) or the first ip returned  when using gethostbyname() on the hostname()).  But we also propose allowing users to specified the "preferred subnet string" as an option using the HG_init_opt() API.   For example, a preferred subnet string "10.93/16" would indicate we want the default IP address to be one on the 10.93 subnet.

1. attempting to use HG_Init to bind to a bad hostname/IP should fail.  e.g. HG_Init("bmi+tcp://bogus.id", HG_TRUE) should fail.

A quick survey of NAs shows the following behavior:
<pre>
  na_info_string             binds to            HG_Addr_to_string
  -----------------          -------------       ------------------
  bmi+tcp://10.93.1.57       0.0.0.0:22222       bmi+tcp://rr57:22222 (bound to INADDR_ANY)
  bmi+tcp://0.0.0.0:5000     0.0.0.0:5000        bmi+tcp://0.0.0.0:5000 (Addr to strings ret 0.0.0.0)
  (next one is when port 5000 is already claimed by another process...
   this should fail with something like "Address in use" but instead it
   does the below ...)
  bmi+tcp://10.93.1.57:5000  0.0.0.0:5001        bmi+tcp://10.93.1.57:5001 (should fail)
  bmi+tcp://bogus.id         0.0.0.0:22222       bmi+tcp://bogus.id:22222 (should fail)

  ofi+tcp                    10.92.1.57:37821 ofi+tcp;ofi_rxm://10.92.1.57:37821 (ignored INADDR_ANY)
  (next one is when port 5000 is already claimed by another process...)
  ofi+tcp://10.93.1.57:5000   -- program Aborts with 'free(): invalid pointer'--

  ofi+tcp://bogus.id         10.92.1.57:46105 ofi+tcp;ofi_rxm://10.92.1.57:46105 (should fail)
  ofi+tcp://bogus.id:5000    10.92.1.57:40657 ofi+tcp;ofi_rxm://10.92.1.57:40657 (should fail, ignored 5000)
</pre>

Merge request #331 fixes some of the BMI issues.

**Comment by chuckcranor** [comment]
I wrote a test program to check the IP handling behavior of NAs. attached:
[mercury-testurl-tcpip.c.txt](https://github.com/mercury-hpc/mercury/files/4216298/mercury-testurl-tcpip.c.txt)

this tests HG_Init() with various tcp/ip na_info_string params.  as part of program startup, we first collect the current node's network config using getifaddrs(3).  we then pick a bad IP address (one that you cannot bind(2) to because isn't attached to any of our network interfaces) and an invalid hostname for testing.  we can then start generating na_info_strings and testing them.

to test, the main program forks off a subprocess that calls HG_Init() and returns the result.   the main process communicates with subprocesses using a socketpair and the waitpid() status value.  we sanity check mercury IP addressing using the output of "netstat -a -n" when possible.

**Comment by chuckcranor** [comment]
I've created a prototype implementation of Mercury subnet selection using HG_Init_opt() as i've outlined previously.  It's pretty small (diff attached).

sample usage:

<pre>
int main(int argc, char **argv) {
   hg_class_t *h;
   struct hg_init_info hgiinfo;
   if (argc != 2 && argc != 3) exit(1);

   memset(&hgiinfo, 0, sizeof(hgiinfo));
   if (argc == 3) hgiinfo.na_init_info.pref_subnet = argv[2];
   printf("calling init: %s, subnet-spec=%s\n", argv[1], 
       (argc == 3) ? hgiinfo.na_init_info.pref_subnet : "<none>");
   h = HG_Init_opt(argv[1], HG_TRUE, &hgiinfo);
   /// ...
}
</pre>

so it runs like this:

<pre>
    % ./testin bmi+tcp 
    calling init: bmi+tcp, subnet-spec=<none>
    GOT: bmi+tcp://10.92.1.57:34327
    % 
    % ./testin bmi+tcp 10.93/16
    calling init: bmi+tcp, subnet-spec=10.93/16
    GOT: bmi+tcp://10.93.1.57:35309
    % 
    % ./testin bmi+tcp 127/8
    calling init: bmi+tcp, subnet-spec=127/8
    GOT: bmi+tcp://127.0.0.1:39271
    % 
    % ./testin bmi+tcp 10.93.1.57
    calling init: bmi+tcp, subnet-spec=10.93.1.57
    GOT: bmi+tcp://10.93.1.57:37057
    % 
</pre>


the changes are:

<pre>
  - add two new na functions: NA_Parse_subnet() and NA_Pref_ipaddr().
    the first parses a subnet spec into a subnet and netmask, the
    second applies a subnet and netmask to the current set of active
    interfaces on the system.

  - added: const char *pref_subnet;            /* Preferred IP subnet */
    to structure "na_init_info"

  - to BMI: I pulled in the changes from Phil's "dev-bmi-urls" branch.

    on top of Phil's changes I had the BMI init function call 
    NA_Parse_subnet() and NA_Pref_ipaddr() if BMI has been asked 
    to bind to INADDR_ANY.
    
    i also modified addr to string to catch "0.0.0.0" self addresses and
    plug in the preferred IP address instead.
</pre>


the attached "PREF-DIFF.txt" is the entire set of changes.  I also included "POST-BMI-DIFF.txt" which is the just the changes I made to Phil's "dev-bmi-urls" na_bmi.c.

[POST-BMI-DIFF.txt](https://github.com/mercury-hpc/mercury/files/4216329/POST-BMI-DIFF.txt)
[PREF-DIFF.txt](https://github.com/mercury-hpc/mercury/files/4216330/PREF-DIFF.txt)

**Comment by soumagne** [comment]
@chuckcranor sorry again for the delay. I'm finally getting to those changes now.
