### ISSUE TITLE
more helpful error message on permission failure in na+sm

### ISSUE THREAD

**Issue by carns** [mercury-hpc/mercury#344]
**Is your feature request related to a problem? Please describe.**

If you try to do a bulk transfer with a CMA-enabled na+sm transport but the processes don't have permission to access each other's memory, then you get an error message like this:

```
# NA -- Error -- /tmp/carns/spack-stage/spack-stage-mercury-master-3ymbyrkaesrdvj6a5vytsrtnc5yw3arz/spack-src/src/na/na_sm.c:3761
 # na_sm_put(): process_vm_writev() failed (Operation not permitted)
# HG -- Error -- /tmp/carns/spack-stage/spack-stage-mercury-master-3ymbyrkaesrdvj6a5vytsrtnc5yw3arz/spack-src/src/mercury_bulk.c:791
 # hg_bulk_transfer_pieces(): Could not transfer data (NA_PROTOCOL_ERROR)
# HG -- Error -- /tmp/carns/spack-stage/spack-stage-mercury-master-3ymbyrkaesrdvj6a5vytsrtnc5yw3arz/spack-src/src/mercury_bulk.c:952
 # hg_bulk_transfer(): Could not transfer data pieces
# HG -- Error -- /tmp/carns/spack-stage/spack-stage-mercury-master-3ymbyrkaesrdvj6a5vytsrtnc5yw3arz/spack-src/src/mercury_bulk.c:1793
 # HG_Bulk_transfer_id(): Could not start transfer of bulk data
```

The solution (at least on a workstation/laptop that isn't configured to allow the above already) is to do the following, or similar, as root:

```
# echo 0 > /proc/sys/kernel/yama/ptrace_scope
```

This isn't likely to be obvious to end-users, particularly if the sm transport is automatically activated for intra-node communication.

**Describe the solution you'd like**
A longer clear error message, ideally at init time but if not at init time then at bulk transfer time.

For comparison, libfabric has this check when initializing their shm provider:

https://github.com/ofiwg/libfabric/blob/master/prov/shm/src/smr_init.c#L76

There is also some discussion of the pros/cons of runtime testing of vm_writev() here as an alternative:

https://github.com/ofiwg/libfabric/pull/5510

**Comment by soumagne** [comment]
@carns Just wanted to get back to that issue. We do the following check at configure time:
```
if(NA_SM_HAS_CMA)
  execute_process(COMMAND /usr/sbin/sysctl -n kernel.yama.ptrace_scope
    OUTPUT_VARIABLE NA_SM_YAMA_LEVEL ERROR_VARIABLE NA_SM_YAMA_SYSCTL_ERROR)
  if(NOT NA_SM_YAMA_SYSCTL_ERROR) # Yama is present
    if(NA_SM_YAMA_LEVEL EQUAL 1)
      message(WARNING "Kernel Yama configuration only allows NA SM restricted cross-memory attach, please refer to the mercury documentation for more details.")
    elseif(NA_SM_YAMA_LEVEL GREATER 1)
      message(FATAL_ERROR "Kernel Yama configuration does not allow NA SM cross-memory attach, for more details please refer to: https://www.kernel.org/doc/Documentation/security/Yama.txt.")
    endif()
  endif()
endif()
```
Which means we allow for the value 1 to be set, which may be what most people encountering that issue have set since it passed the configure check (though probably issuing a warning). If 1 is set, you should do the following in your program:
```C
#include <sys/prctl.h>
prctl(PR_SET_PTRACER, PR_SET_PTRACER_ANY, 0, 0, 0);
```

**Comment by carns** [comment]
The population of people who will notice that warning at configure time is probably pretty small.  It's also tricky to map configure-time conditions (likely on a login node) to runtime conditions (likely on a compute node).

At any rate, I don't have a problem with the configure-time warning, but a descriptive error message at runtime might save more support emails :)
