### ISSUE TITLE
NA SM: enable automatic SM routing by default?

### ISSUE THREAD

**Issue by carns** [mercury-hpc/mercury#345]
**Is your feature request related to a problem? Please describe.**

If I'm reading the code correctly, to enable this feature you must do two things:

* set the MERCURY_USE_SM_ROUTING option in cmake at build time
* set the hg_init_info->auto_sm flag at run time by calling HG_Init_opt() when starting Mercury

I don't believe that there is a spack variant to enable the former, so there isn't at present a way to enable this feature unless you are doing a manual build.

**Describe the solution you'd like**

At a minimum it would be nice to make this easier to enable; maybe a spack variant that not only enables the feature at build time but makes it activate automatically unless the user opts *out* with an HG_Init_opt() rather than opting in.

Even better would be if both the build option and the runtime option were on by default.  Is there any known down side to doing so?

If we have any NA modules that are not compatible with sm routing, can we emit a warning and then simply disable sm?  The warning can indicate that users can opt out (and silence the warning) by changing the cmake default parameter value from true to false, or by switching to an na that doesn't have this limitation.

**Additional context**

I can help with testing (performance and functional) if this seems like a reasonable thing to do.

**Comment by soumagne** [comment]
With the latest changes that were brought to 2.0.0rc2, overheads associated to that option have been greatly decreased so it should be ok to keep it ON by default and delete the cmake option.

There are still 2 potential issues though with enabling the runtime option by default (i.e. through HG_Init_opt):
1. it will make NA plugins that don't expose a file descriptor like BMI busy spin. 
2. there are additional completion queues to check and memory consumption is increased

**Comment by carns** [comment]
Ok, it sounds like at a minimum we can go ahead and toggle the cmake default without hurting anything then, right?

The runtime option is a conundrum.  If the active transports can handle it without busy spinning it would be nice to turn it on, but that would disrupt BMI users.  Tagging @chuckcranor to comment. 

Could it be disabled automatically if the BMI NA is activated?  I'm not sure if that makes any sense; just asking.  That would probably be manifested as 3 possible values for the na opt field that map to "on", "off", or "automatic".  The first two brute force it one way or the other (so even BMI users could use it if they were in a scenario where the busy spinning was warranted).  The default would be automatic, which turns it on unless BMI is being used.

**Comment by soumagne** [comment]
That's right, I might just still keep the toggle but only for debugging purposes so it will be hidden.

OK I think I like the idea of adding a third "auto" value for that field.

**Comment by chuckcranor** [comment]
I think having this compiled in by default is fine.

But it might be better for this to be something that you opt in to at runtime rather than turning it on by default:

- forcing BMI to spin would be bad
- changing the default setting breaks backward compatibility
- some transports may not need it.  for example, PSM and PSM2 already have their own shared memory transport built in using their "Packet Transport layers" interface (doing it at the Mercury layer would be redundant).

**Comment by chuckcranor** [comment]
for reference: https://github.com/intel/psm/blob/master/ptl.h#L49
<pre>
/* We currently have 3 PTLs, 0 is reserved. */
#define PTL_DEVID_IPS  1
#define PTL_DEVID_AMSH 2
#define PTL_DEVID_SELF 3
</pre>

I believe PTL_DEVID_IPS is the network, PTL_DEVID_AMSH  corresponds to Mercury "na+sm," and PTL_DEVID_SELF corresponds to Mercury "HG_HAS_SELF_FORWARD."

**Comment by carns** [comment]
> I think having this compiled in by default is fine.
> 
> But it might be better for this to be something that you opt in to at runtime rather than turning it on by default:
> 
>     * forcing BMI to spin would be bad
> 
>     * changing the default setting breaks backward compatibility
> 
>     * some transports may not need it.  for example, PSM and PSM2 already have their own shared memory transport built in using their "Packet Transport layers" interface (doing it at the Mercury layer would be redundant).

This suits me fine.  For the use cases I'm interested in we can toggle this at the Margo level depending on the transport/deployment configuration.

**Comment by soumagne** [comment]
@carns see commit 5e6e6ad, there's no more CMake option, just the toggle at runtime, assuming you have compiled mercury with the NA SM plugin.
