### ISSUE TITLE
Warning when registering an RPC with an already used id

### ISSUE THREAD

**Issue by mdorier** [mercury-hpc/mercury#351]
It would be useful if Mercury could print a warning if `HG_Register` is called with an id that is already used. That way we would catch (1) programming errors when the wrong id is passed to `HG_Register`, and (2) composition errors when multiple mercury-based libraries conflict on using the same id, and (3) name-hashing error when RPCs registered with different names actually end up with the same hash.

**Comment by carns** [comment]
It probably needs to be legal to register twice as long as the encoding functions don't change (thinking about the case where one process initializes both a client library and server library, with the difference being that one does not provide a handler fn pointer).

I can't think of a scenario where it would be purposeful to re-register and RPC with different encoding functions, though.  That should generate at least a warning, probably a full error.

**Comment by mdorier** [comment]
That's right.

**Comment by soumagne** [comment]
Fixed in 658744a6818e581125e1caf5bc2ec13070646208
