### ISSUE TITLE
NA OFI: Response to RPC not working when using tcp://127.0.0.1

### ISSUE THREAD

**Issue by mdorier** [mercury-hpc/mercury#359]
I have Mercury compiled with ofi+tcp support. I'm running a server and a client both on a local Debian machine.

Working scenario: I initialize Mercury in the server with "tcp". I have the server print its address. I then start the client, passing the server's address as program argument. The client initializes Mercury with "tcp" as well. The client is then able to lookup the server's address, send an RPC, and get the response back from the server.

Non-working scenario: I initialize the server with "tcp://127.0.0.1:1234". The server print its address: I can confirm its address is "ofi+tcp;tcp_rxm://127.0.0.1:1234". The client is still initialized with just "tcp". The client is able to lookup the server's address, send an RPC (which is correctly received and executed by the server), however it hangs waiting on the response.

**Comment by soumagne** [comment]
I believe this is related to https://github.com/mercury-hpc/mercury/issues/332

**Comment by soumagne** [comment]
@mdorier if you could try again with latest libfabric, I believe this was fixed. I'd just like to close that issue.

**Comment by soumagne** [comment]
@mdorier I spent more time looking at that and for it to work you need the client to be initialized on the same interface. That might be a libfabric defect but if both client and server are using the same "lo" interface it works fine. Closing that issue as this is not an issue per se.
