### ISSUE TITLE
Compile error with GCC 10 in src/na/na_plugin.h

### ISSUE THREAD

**Issue by bnicolae** [mercury-hpc/mercury#362]
GCC 10+ considers redefinition of global variables an error. This affects na_plugin.h, which apparently is used in multiple places. The correct solution is to avoid global variables altogether if possible, declare them static or as a last resort move them from headers into a single source file and refer to them from everywhere else using the "extern" keyword.

However, a quick hack is also possible by using the "common" attribute as follows:

`/*********************/`
`/* Public Variables */`
`/*********************/`
`#ifdef NA_HAS_SM`
`__attribute__((__common__)) NA_EXPORT NA_PLUGIN_OPS(sm);`
`#endif`

**Comment by bnicolae** [comment]
Nevermind, the master branch has fixed it. Can we have a release with this fix? This would help with automating installations.

**Comment by soumagne** [comment]
@bnicolae right I had fixed that. I'm currently working on it so you should not have to wait for too long now before having a new release that you can use.
