### ISSUE TITLE
mercury.pc contains MERCURY_LIBRARY-NOTFOUND

### ISSUE THREAD

**Issue by calccrypto** [mercury-hpc/mercury#370]
**Describe the bug**
Since 550423af6a76e2b87bccd8909cefef7de461b090, the mercury.pc file has been generated with `Libs: -L${libdir}  -lmercury_hl -lmercury -lMERCURY_LIBRARY-NOTFOUND -lmercury_util -lna`.

**To Reproduce**
1. `git checkout 550423af6a76e2b87bccd8909cefef7de461b090` or `git checkout master && git pull`
2. `mkdir -p build && cd build && rm -rf *`
3. `cmake .. -DCMAKE_INSTALL_PREFIX=$SWHOME/mercury && make && make install`
4. `cat $SWHOME/mercury/lib/pkgconfig/mercury.pc` or `pkg-config --libs mercury`

**Expected behavior**
The mercury.pc file should contain `Libs: -L${libdir}  -lmercury_hl -lmercury -lmchecksum -lmercury_util -lna`.

**Platform (please complete the following information):**
 - CentOS 7
 - gcc-8, gcc-9
 - No/Any plugin
- CMake 3.17

**Comment by soumagne** [comment]
hmm I was pretty sure that I had that sorted out. Could you please make sure that you've done a git submodule update?

**Comment by calccrypto** [comment]
That fixed it.
