### ISSUE TITLE
NA OFI: reaches MR limit w/udreg using GNI provider

### ISSUE THREAD

**Issue by mdorier** [mercury-hpc/mercury#386]
**Describe the bug**

A program that used to work fine with Mercury 2.0.0a1 now gives me the following error with HG_Bulk_create:

```
# NA -- Error -- /tmp/mdorier/spack-stage/spack-stage-mercury-master-frinibkhaabvsaodykdoftxe26s2vocg/spack-src/src/na/na_ofi.c:4183
 # na_ofi_mem_register(): fi_mr_reg() failed, rc: -5 (Input/output error)
# HG -- Error -- /tmp/mdorier/spack-stage/spack-stage-mercury-master-frinibkhaabvsaodykdoftxe26s2vocg/spack-src/src/mercury_bulk.c:435
 # hg_bulk_create(): NA_Mem_register() failed (NA_PROTOCOL_ERROR)
# HG -- Error -- /tmp/mdorier/spack-stage/spack-stage-mercury-master-frinibkhaabvsaodykdoftxe26s2vocg/spack-src/src/mercury_bulk.c:1016
 # HG_Bulk_create(): Could not create bulk handle
```

I have little more information yet, I prefer to post this issue right now to prevent potentially releasing Mercury 2.0.0 with a regression.

**Platform (please complete the following information):**
 - System description: Theta
 - Compiler version: gcc 9.3.0 and gcc 7.3.0
 - Plugin and protocol used: ofi+gni
 - Dependency version: libfabric@1.10.1

**Additional context**

I'm trying to reduce down this problem to a simple program that can reproduce it, but in the mean time I here is a description of what I'm doing:

I'm using HEPnOS which is built on top of SDSKV, Margo, and finally Mercury. The client program issues `sdskv_put_packed` operations, which essentially registers a bulk handle for a contiguous buffer and forwards an RPC to a remote server. The clients consist of 896 processes on 112 nodes (8 per node). The servers consist of 32 processes on 16 nodes (2 per node). Each server manages 4 databases. When a client process has to write data into HEPnOS, it creates one ULT per database (so 128 ULTs in this configuration), each issuing its own `sdskv_put_packed` operation. This is where some of these `sdskv_put_packed` fail when trying to register the memory, giving the above error.

This experiment is working fine with Mercury 2.0.0a1, all other dependencies remaining the same. It fails with 2.0.0rc1 (same error as master).

Note: a setting that currently works right now is if there is not a lot of data to write, i.e. if the data is such that only 50 processes out of the 896 have something to write, then it works fine. I have tried with enough data for 448 processes to have something to write and it fails. I don't know where is the cut-off number of processes where things start failing.

Currently planned experiments: I'll try with 1 client node issuing the whole workload (so all 8 processes on that node will have something to write) and I'll try with 112 nodes but only 1 process per node. My idea being to check if there is a limit on the total number of registered segments on a single node at any given point.

**Comment by carns** [comment]
@soumagne is there any way to query the memory registration limit for a given provider/na?

If so, we could do a quick hack to print the value and keep a counter in margo to warn when we approach it (to see if this is a deterministic transport limit problem).

If that were it then we could throttle at some level.  It is simple to make a margo operation block until some condition is met, but we need to know for sure if that's what the problem is before making a change like that.

**Comment by soumagne** [comment]
Weird, I don't see anything that would cause that issue, it seems to me that you're just hitting the limit, there should not be any difference between rc1 and a1 in that regard. If you have a reproducer yes that would help though. I can also look at printing that limit / return an error early if that's possible. On another note I'm almost done with the changes to support non contiguous memory registration, would that help you?

**Comment by mdorier** [comment]
Non-contiguous registration wouldn't help in this particular case. I'll continue searching for the problem...

**Comment by soumagne** [comment]
OK. Can you try to set FI_LOG_LEVEL=debug and post the log when it fails?

**Comment by soumagne** [comment]
Also you had asked that question on mercury mailing list before and Howard had suggested that you try also export UGNI_DEBUG=10

**Comment by soumagne** [comment]
I would expect that you see something in the log that says that udreg has hit the registration limit.

**Comment by soumagne** [comment]
@carns it looks like that limit can be queried through `domain_attr->mr_count`

**Comment by carns** [comment]
Looks like the field name is `mr_cnt`.  FWIW GNI is advertising that value as 64k:

```
[carns@carns-x1-7g gni (master)]$ grep -Ir mr_cnt .
./src/gnix_fabric.c:	gnix_info->domain_attr->mr_cnt = 65535;
```
I'm not sure if that is an accurate value, though.  I expected it to be in turn queried from GNI rather than hardcoded.

**Comment by carns** [comment]
Maybe it would be helpful if Mercury tracked registered memory (both in terms of bytes and number of registrations) by incrementing and decrementing per-class atomics on bulk_create() and bulk_free().  Then if a registration failed it could print the values as part of the error message?

That might help with diagnostics to get a feel for what the conditions were like when one of those calls failed.  Thinking on it a little more it is hard to say which process hit it and if it was a transport limitation or a physical memory limitation.

**Comment by soumagne** [comment]
Ah sorry my bad I meant to write `mr_cnt` and not `mr_count` :) right I really don't think that's an accurate value though. UDREG's MR cache limit is much lower than that, around 4096 maybe.

**Comment by soumagne** [comment]
Yes we could do that, I will add tracking of memory registration so that we have a more helpful error when it fails.

**Comment by mdorier** [comment]
(Sorry for the late response about posting logs with `FI_LOG_LEVEL=debug` and `UGNI_DEBUG=10`; my job has been queuing on Theta for the past 2 days. I'll edit this message when it finally runs.)

**Comment by mdorier** [comment]
I finally got a trace of the run with GNI and libfabric debugging ON.
You can download it [here](https://drive.google.com/file/d/1W36YcaYAXbh2ZrLUNmf9ENmh_qcNmddN/view?usp=sharing). It's 100MB compressed; about 2GB uncompressed.

**Comment by soumagne** [comment]
ok :) we might only need the part before it fails though but thanks I will take a look.

**Comment by mdorier** [comment]
Sorry, I looked into it but couldn't figure out which messages indicate something fishy. You can search for "HG" to get the first errors messages from Mercury.

**Comment by soumagne** [comment]
Possibly linked to commit f026fac631ffde6787beaad2a17fb5ff8da26bf4 that was added by @roblatham00 to reduce udreg limit. We might need to work around that limit again, I don't really have a good answer right now since it depends on the situation, i.e., depends on ratio processes per node / registrations done per process.

**Comment by soumagne** [comment]
I guess a temporary solution would be as @carns mentioned to track that number of registrations and print a more sensible error message for now, saying that this limit needs to be increased if reached.

**Comment by carns** [comment]
I think the statistics  and error message would be a good diagnostic at least.  Right now we are kind of speculating about what went wrong, but if we saw statistics when the error occurs then we could probably confirm or rule out some things.  Cases like this take too long to run for us to try many ideas to fix it :)

**Comment by soumagne** [comment]
Agree, @mdorier confirmed to me that reverting f026fac631ffde6787beaad2a17fb5ff8da26bf4 fixes his issue though. Beyond the diagnostic fix I'm trying to think what would be a better solution than setting another environment variable, I feel like we already have for too many to set and remember between OFI and the underlying protocols that it's already a pain to keep track of them.

**Comment by soumagne** [comment]
Tracking of MR handles was added in #399
