### ISSUE TITLE
HG Bulk: excessive memory allocations in bulk_create path with na_sm

### ISSUE THREAD

**Issue by carns** [mercury-hpc/mercury#390]
**Describe the bug**
This is a low priority, just noting in an issue so that we can remember to look at it at some point down the road.

I think that hg_bulk_create() in the (probably?) most common single-segment case calls malloc() or calloc() at least 5 times.

In hg_bulk_create() there is one to create the hg_bulk struct, one to create the segments array, and one to create the na_mem_handles.

Once it enters na_sm_mem_handle_create_segments() it then does one allocation to create the na_sm_mem_handle and one to create the iov array.

Probably some of these could be collapsed, maybe with flexible array members in parent structs or something similar.

I don't have a benchmark that exhibits this as a performance problem, I just mistakenly looked down this path while investigating something else and thought I would note it in an issue.

**Comment by soumagne** [comment]
Yes I was actually looking at those as part of the non-contiguous changes that I've been making for OFI. I'm almost done with those changes.

**Comment by soumagne** [comment]
I'll let you know when the PR is up and you can have a look.

**Comment by soumagne** [comment]
Fixed in #399
