### ISSUE TITLE
NA OFI: listen starts on random port for verbs

### ISSUE THREAD

**Issue by missiongoogle** [mercury-hpc/mercury#435]
I am trying to start mercury for verbs at a specific port:
`HG_Core_init_opt(): Initializing with verbs://mlx4_0:1257, listen=1
`

but listen starts every time on some random port:

```
HG_Core_addr_to_string(): Generated string "ofi+verbs;ofi_rxm://10.8.8.8:48877" from address (0x26f7250)
svr address string: "ofi+verbs;ofi_rxm://10.8.8.8:48877"
```

For TCP, it works fine. Listen starts on the user specified port.

Is there any way to instruct mercury to use port given by the user?

**Comment by soumagne** [comment]
Yes make sure you provide an IP/iface along with the port, e.g.: `verbs://mlx4_0/ib0:1257` or `verbs://mlx4_0/10.8.8.8:1257`

**Comment by missiongoogle** [comment]
> Yes make sure you provide an IP/iface along with the port, e.g.: `verbs://mlx4_0/ib0:1257` or `verbs://mlx4_0/10.8.8.8:1257`

It worked. Thanks!
Can you please explain the logic behind this?

If I specify only ip / iface:port, then also it fails, E.G. `verbs://ib0:1257` fails but `tcp:///eth1:1257` succeeds for TCP. Why is the verbs behaviour not consistent with the other protocols?

**Comment by soumagne** [comment]
`mlx4_0` in that case represents a device / port name that is then mapped to a libfabric domain name. To be able to bind to a specific port, we need an interface name or IP address. It's surprising though that `verbs://ib0:1257` fails, I don't see any reason for it not to succeed, the only downside is that it would pick the first available device / domain in the list (that you specify here using `mlx4_0`). I will double check.

**Comment by soumagne** [comment]
@missiongoogle sorry for the delay in getting to that one, there was definitely something wrong with verbs and latest master should address the consistency issue, i.e. you can do `verbs://ib0:1257`.
