### ISSUE TITLE
NA SM: to lookup address which isn't exists in the hash table makes memory leak

### ISSUE THREAD

**Issue by KoyamaSohei** [mercury-hpc/mercury#445]
**Describe the bug**
In `na+sm`, when mercury try to lookup address which isn't exists in the hash table, mercury insert that into hash table. 

https://github.com/mercury-hpc/mercury/blob/4325efabcdaf5d0a8847015aac7ab9c168f9b38b/src/na/na_sm.c#L3822

At this time, the reference counter is initialized to 1 in `na_sm_addr_create`

https://github.com/mercury-hpc/mercury/blob/4325efabcdaf5d0a8847015aac7ab9c168f9b38b/src/na/na_sm.c#L2381

However, in `na_sm_addr_lookup`, increment reference counter, so `&na_sm_addr->ref_count` becomes 2.

https://github.com/mercury-hpc/mercury/blob/4325efabcdaf5d0a8847015aac7ab9c168f9b38b/src/na/na_sm.c#L3836

After that, in `na_sm_addr_free`, the reference counter is decremented, not released yet because it is not 0.

https://github.com/mercury-hpc/mercury/blob/4325efabcdaf5d0a8847015aac7ab9c168f9b38b/src/na/na_sm.c#L3855

Eventually the address will not be released and will result in a memory leak.

**To Reproduce**

- `"na+sm://4661/0" ` is dummy address
- use [AddressSanitizer](https://github.com/google/sanitizers/wiki/AddressSanitizer) to detect memory leak
```
$ cat main.c
#include <mercury.h>
#include <assert.h>

int main() {
  na_class_t *class;
  na_addr_t addr = NA_ADDR_NULL;

  NA_Set_log_level("debug");

  class = NA_Initialize("na+sm",NA_FALSE);
  assert(class != NULL);

  assert(NA_Addr_lookup(class,"na+sm://4661/0",&addr)==NA_SUCCESS);

  assert(NA_Addr_free(class,addr)==NA_SUCCESS);
  assert(NA_Finalize(class)==NA_SUCCESS);
}
$ gcc -Wall -g `pkg-config --cflags mercury` -fsanitize=address -fno-omit-frame-pointer main.c `pkg-config --libs mercury` -fsanitize=address
$ ASAN_OPTIONS="abort_on_error=1" ./a.out 
...
==4735==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 72 byte(s) in 1 object(s) allocated from:
    #0 0x7f236cf5c639 in __interceptor_calloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x7f236ce564f2 in na_sm_addr_create mercury/src/na/na_sm.c:2376
```

**Expected behavior**

 `&na_sm_addr->ref_count` is expected to be 1 after `na_sm_addr_lookup`

**Platform (please complete the following information):**
 - Linux
 - gcc version 10.2.0 
 - Plugin and protocol: na+sm

**Comment by soumagne** [comment]
@KoyamaSohei thanks for reporting the issue and opening the PRs. Sorry for not getting back to you earlier, I will have a look at this today.

**Comment by KoyamaSohei** [comment]
@soumagne  I hope you don't mind, and thanks for taking your precious time to me!
