### ISSUE TITLE
Header mercury_atomic.h no longer builds with C++ compilers

### ISSUE THREAD

**Issue by alberto-miranda** [mercury-hpc/mercury#449]
Including `mercury_atomic.h` directly or indirectly (e.g. by including `mercury_log.h`) causes builds to fail with a C++ compiler.  The errors are all related to the atomic types and are similar to the log below:

```shell
make
[ 10%] Built target common
[ 15%] Building CXX object examples/00_hello_world/CMakeFiles/00_hello_world_server.dir/server.cpp.o
In file included from /home/amiranda/var/projects/hermes/prefix/include/mercury_atomic.h:34,
                 from /home/amiranda/var/projects/hermes/prefix/include/mercury_dlog.h:16,
                 from /home/amiranda/var/projects/hermes/prefix/include/mercury_log.h:85,
                 from /home/amiranda/var/projects/hermes/repo/include/hermes/detail/mercury_utils.hpp:6,
                 from /home/amiranda/var/projects/hermes/repo/include/hermes/exposed_memory.hpp:21,
                 from /home/amiranda/var/projects/hermes/repo/include/hermes/async_engine.hpp:28,
                 from /home/amiranda/var/projects/hermes/repo/include/hermes.hpp:4,
                 from /home/amiranda/var/projects/hermes/repo/examples/00_hello_world/server.cpp:7:
/usr/lib/gcc/x86_64-linux-gnu/9/include/stdatomic.h:40:9: error: ‘_Atomic’ does not name a type
   40 | typedef _Atomic _Bool atomic_bool;
      |         ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/9/include/stdatomic.h:41:9: error: ‘_Atomic’ does not name a type
   41 | typedef _Atomic char atomic_char;
      |         ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/9/include/stdatomic.h:42:9: error: ‘_Atomic’ does not name a type
   42 | typedef _Atomic signed char atomic_schar;
      |         ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/9/include/stdatomic.h:43:9: error: ‘_Atomic’ does not name a type
   43 | typedef _Atomic unsigned char atomic_uchar;
      |         ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/9/include/stdatomic.h:44:9: error: ‘_Atomic’ does not name a type
   44 | typedef _Atomic short atomic_short;
      |         ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/9/include/stdatomic.h:45:9: error: ‘_Atomic’ does not name a type
   45 | typedef _Atomic unsigned short atomic_ushort;
      |         ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/9/include/stdatomic.h:46:9: error: ‘_Atomic’ does not name a type
   46 | typedef _Atomic int atomic_int;
      |         ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/9/include/stdatomic.h:47:9: error: ‘_Atomic’ does not name a type
   47 | typedef _Atomic unsigned int atomic_uint;
      |         ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/9/include/stdatomic.h:48:9: error: ‘_Atomic’ does not name a type
   48 | typedef _Atomic long atomic_long;
      |         ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/9/include/stdatomic.h:49:9: error: ‘_Atomic’ does not name a type
   49 | typedef _Atomic unsigned long atomic_ulong;
      |         ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/9/include/stdatomic.h:50:9: error: ‘_Atomic’ does not name a type
   50 | typedef _Atomic long long atomic_llong;
      |         ^~~~~~~
``` 

The reason why this is happening is that `<stdatomic.h>` cannot be used directly in C++, which has its own implementation with differently named types (see https://stackoverflow.com/questions/45342776/how-to-include-c11-headers-when-compiling-c-with-gcc, https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60932, and https://bugs.python.org/issue23644).

I'm attaching a patch that makes it build with a C++ compiler by falling back to `std::atomic`, which should be equivalent and is the recommended approach.

[mercury_atomic_patch.txt](https://github.com/mercury-hpc/mercury/files/6335752/mercury_atomic_patch.txt)

**Comment by soumagne** [comment]
Thanks @alberto-miranda for the path, @chuckcranor was actually mentioning that problem to me. Chuck, what do you think of this approach? Would that also work for you?

**Comment by alberto-miranda** [comment]
Sure, no problem. I'm uploading a V2 for the patch since we found some additional problems with G++ 8.3.0.

[mercury_atomic.v2.patch.txt](https://github.com/mercury-hpc/mercury/files/6337513/mercury_atomic.v2.patch.txt)

**Comment by chuckcranor** [comment]
> Thanks @alberto-miranda for the patch, @chuckcranor was actually mentioning that problem to me. Chuck, what do you think of this approach? Would that also work for you?

My concern was that comment 13 in https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60932 where it says:
<pre>
> What prevent stdatomic.h to detect if it is included in C++ mode and
> includes C++ &lt;atomic&gt; instead?

Even if it did that, it wouldn't guarantee that C's atomic_int and C++'s std::atomic_int are compatible. 
So you'd still need to rely on non-portable implementation-specific assumptions.
</pre>

should that be a worry?

**Comment by soumagne** [comment]
I created a PR based on your fix and this page: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0943r1.html
I think in general we should avoid exposing atomic types in mercury headers since the util library is compiled using a C compiler and doing that implies that there's interoperability between C/C++ compilers, that's only an assumption that we can make and there's no real guarantee for it. Anyway since that only concerns the debug log, it's probably just okay.
