### ISSUE TITLE
HG Bulk: hg_bulk_op_pool_get deadlocks

### ISSUE THREAD

**Issue by otatebe** [mercury-hpc/mercury#462]
**Describe the bug**
hg_bulk_op_pool_get deadlocks

**backtrace**
backtrace is attached

**Problem**
cond_wait should be called in the while statement not the if statement:
https://github.com/mercury-hpc/mercury/blob/master/src/mercury_bulk.c#L1847
This if should be while

When it is the if statement, data race happens in the following section.
https://github.com/mercury-hpc/mercury/blob/master/src/mercury_bulk.c#L1855

**Attachment**
[hg_bulk_op_pool_get-deadlock.txt](https://github.com/mercury-hpc/mercury/files/6513296/hg_bulk_op_pool_get-deadlock.txt)

**Comment by soumagne** [comment]
Thanks for reporting the issue. The problem is not the if/while since there's a continue that also takes care of spurious wakeups, it was just missing an unlock.
