### ISSUE TITLE
Query regarding the Bulk Transfer for verbs plugin

### ISSUE THREAD

**Issue by missiongoogle** [mercury-hpc/mercury#467]
I have some doubts regarding the bulk transfer mechanism supported by Mercury:

1. In the overview section of [documentation](https://mercury-hpc.github.io/documentation/), it is mentioned that RPC layer is used for small messages. What is the maximum size that this transfer supports? Also, are the messages with small length sent with ibv_send_inline (not registering the memory region) method for verbs?
2. For bulk transfer, with verbs, is there a way to provide a previously registered MR region. In the examples, I see that the user is allocating the memory using malloc / calloc and sending the same buffer in the API. HG_Bulk_Create() registers the buffer as MR region. Can the same region be used again for data transfer?

**Comment by soumagne** [comment]
1. Maximum size depends on the underlying transport, it can be queried using HG_Class_get_input_eager_size(). We do not call into verbs directly but rely on OFI to do that, which calls ibv_post_send(). You do not need to worry about memory registration at this level. When needed, registration is done internally.
2. You can call HG_Bulk_create() once and then do multiple transfers with it, that's right. It is actually recommended that you do it this way, outside of your transfer code path to avoid memory registration overheads.

**Comment by missiongoogle** [comment]
Thanks for prompt response.

**Comment by missiongoogle** [comment]
I ran HG_Class_get_input_eager_size() and it returned 4060 in my system, it means that HG_Forward can accept this much amount of user payload. But for verbs, the data is still going over RDMA. It means that the OFI will have to internally register the buffer being used in HG_Forward API?
Is this explanation correct? If yes, it would mean that every HG_Forward call will first register the input buffer, thus making the call slow and not desirable in fast path.

**Comment by soumagne** [comment]
We have a pool of pre-registered buffers, when you send a message we use a buffer of that pool, which is why space is limited. There is no registration in that code path for small data.

**Comment by missiongoogle** [comment]
> We have a pool of pre-registered buffers, when you send a message we use a buffer of that pool, which is why space is limited. There is no registration in that code path for small data.

1. What is the size of the pre-registered pool and is it configurable?
2. Is there any queue mechanism within mercury in case of pool going out of space due to many outstanding requests or the request is failed back to the user?
3. If the request if failed, does it make more sense to initialise multiple mercury context with same IP but different port combination to have a larger pool?
