### ISSUE TITLE
An example for mpi plugin

### ISSUE THREAD

**Issue by sktzwhj** [mercury-hpc/mercury#489]
Hi Mercury team, 

I think the current examples in the repo do not really work with MPI plugin. Maybe we need an example of that. My guess is that we need to wrap the client/server code with MPI env init stuff, right?

**Comment by soumagne** [comment]
Hi, the MPI plugin was provided as a testing prototype and I would encourage not to use it as much as possible. Having said that, you don't need to wrap the client/server code with MPI env init stuff, the MPI plugin will do it for you if it's not done.

**Comment by sktzwhj** [comment]
@soumagne Thanks, I see.
