### ISSUE TITLE
How to use the logging infra?

### ISSUE THREAD

**Issue by missiongoogle** [mercury-hpc/mercury#496]
**Describe the bug**
With 1.8.0, I used to invoked HG_Set_log_level("debug") and that used to print all the debug prints in the code path.
With 2.0.1, this does not work. In the README.md, it is mentioned that we need to set the environment variable.
Does this mean that the HG_Set_log_level() is deprecated and just setting up the env variable will enable the debug logs?

**Comment by soumagne** [comment]
Yes that's a known issue with 2.0.1 that was fixed in ee51eda5fb3f66aaa56d6f7cfb828f613e816003. Until there's a new release you can also set the environment variable HG_LOG_SUBSYS to "hg".
