### ISSUE TITLE
ability to automatically choose interfaces by internal node locality

### ISSUE THREAD

**Issue by carns** [mercury-hpc/mercury#540]
**Is your feature request related to a problem? Please describe.**

Some HPC systems have multiple network cards per node.  If all of them are visible, then Mercury will choose the first one advertised by OFI by default unless the user specifies an interface in the Mercury address string.  If all processes use the first interface then the network resources will be underutilized.  If they are selected explicitly then the Mercury user has the burden of trying to figure out which NIC would be most appropriate for each Mercury instance to use.

The Crusher system at the OLCF (https://docs.olcf.ornl.gov/systems/crusher_quick_start_guide.html) is a good example of a system were this could be important.  Each compute node has 4 Slingshot interfaces.  As shown in the node diagram on that page, the NICs are directly attached to GPUs rather than CPUs.  All of them are accessible indirectly from any CPU core, but you can minimize the number of internal bus hops by routing traffic to the NIC/GPU on the local NUMA domain.  Crusher supports a variety of process mappings; it would be nice if the optimal network interface were selected automatically regardless of where a process is launched.

**Describe the solution you'd like**

MPICH (https://github.com/pmodels/mpich/blob/main/src/mpid/ch4/netmod/ofi/ofi_nic.c#L174) and OpenMPI (https://github.com/open-mpi/ompi/blob/master/opal/mca/common/ofi/common_ofi.c#L596) both include logic that consults hwloc to see which, if any, out of a set of potential interfaces has the best locality from a given process.  We should integrate the same capability within Mercury, so that if multiple Mercury instances are executed on the same node without requesting an explicit interface, then they will naturally divide work among interfaces according to architecture locality.  hwloc is the most platform-agnostic solution.

**Describe alternatives you've considered**

Most of the alternatives would be platform-specific (for example, selecting NICs on crusher according to NUMA domain number) and thus difficult to maintain.  Mercury could also select interfaces randomly to increase utilization, but it would not gain the latency and bus utilization benefits of purposefully accounting for locality.

**Additional context**

Selecting interfaces based on locality will only produce an optimal solution if a process is pinned to a set of cores so that it won't migrate somewhere with different locality.  Processes are often pinned on HPC systems already for other reasons, though, and even if the process can hypothetically migrate, the initial locality is still a better guess than random or first-advertised.

**Comment by carns** [comment]
> Hi Phil, For a node with multiple interfaces, would you need to know two things? 1. Of all available interfaces, which can reach my desired destination? 2. Of the interfaces in item (1), which is “closest” to me (assuming I am a process pinned to specific cores)? Hwloc can help with item (2), but did Brice every add support for item (2) (i.e., netloc)? Scott

Hi @scottatchley ,

For the time being I'm personally just worried about 2), assuming that all of the NICs are on the same fully connected fabric for the hosts they might communicate with (this would be good enough for communication among Crusher compute nodes, for example).

1) would be particularly interesting for a router/forwarder/bridge use case, but to my knowledge there isn't anything integrated in Mercury to help manage that right now.  It would probably take help from something atop Mercury to sort out?

**Comment by rajachan** [comment]
OFI provides a fi_nic() interface to pull NIC attributes, including PCI attributes like BDF. With this information from a fi_getinfo() query and hwloc topology info, one can find the NIC closest to the CPU a process is pinned to and open an endpoint with that NIC. This is what the OFI MTL in Open MPI does today.

**Comment by soumagne** [comment]
Thanks @rajachan for pointing out the OFI MTL code, that was definitely helpful.
