### ISSUE TITLE
NA: Add an API function to fetch list of corresponding providers and devices on the system

### ISSUE THREAD

**Issue by kjacque** [mercury-hpc/mercury#544]
**Is your feature request related to a problem? Please describe.**
Currently DAOS is collecting information directly from libfabric to understand how to assign fabric interfaces appropriately to client processes. Now we are adding support for another fabric library (UCX), which we must also query directly. This is the only place where DAOS bypasses Mercury to access fabric information.

**Describe the solution you'd like**
A Mercury function that returns a list of all detected fabric devices and their supported providers. The device here is the OFI domain or UCX device.

I am thinking an array of structures, one per provider per device, something like:

```
struct fabric_dev  {
    char dev_name[MAX_DEV_LEN];
    char provider[MAX_PROVIDER_LEN];
};
```

That is just a suggestion though. In the end we should be able to get a list of all devices and determine which devices support which providers.

**Describe alternatives you've considered**
For now we are querying the fabric libraries directly, bypassing Mercury. It works but it seems like that functionality is a better fit in Mercury's responsibilities.

**Additional context**
`fi_getinfo` is the function we use to collect this info in libfabric. The UCX workflow is more complex. The `ucx_info` tool collects the equivalent information, and makes a good reference: https://github.com/openucx/ucx/tree/master/src/tools/info

**Comment by soumagne** [comment]
Fixed in #680
