### ISSUE TITLE
instrument memory allocations

### ISSUE THREAD

**Issue by carns** [mercury-hpc/mercury#548]
**Is your feature request related to a problem? Please describe.**

There are some code paths in Mercury that will allocate extra memory if needed (for example, to satisfy a request size that exceeds eager message limits).  Some of these are automatic, so it would be helpful for performance debugging to see how often it happens.

**Describe the solution you'd like**

Add a counter to the diag output.

**Describe alternatives you've considered**

**Additional context**

There is also possibly an issue on some platforms with the allocation unit being too big (in some cases it is determine based on system page size), but that's a more subtle problem.  For now just instrumentation would be helpful.

**Comment by soumagne** [comment]
This was added in 2.2.0
