### ISSUE TITLE
Mercury decoders for unions inside input/output structures

### ISSUE THREAD

**Issue by Ngxsharath** [mercury-hpc/mercury#552]
IS it possible to have mercury input and output decoders for unions inside struct (i.e conditionally decode based on type)
`
struct A {

    uint32_t union_type;
    union {

        struct B {
            int a, b, c;
        }
        struct C {
            float temp1, temp2;
       }
     }u_entry;
}`

Example decoder that i would want

`
static HG_INLINE hg_return_t  hg_proc_A(hg_proc_t proc, void *data) {

      hg_return_t ret = HG_SUCCESS;
      struct A *struct_data = ( struct A *)data;

      ret = hg_proc_uint32_t(proc, &struct_data->union_type);
      if (ret != HG_SUCCESS)
            return ret;
      
      /* Based on union type conditionally decode*/
      if( struct_data->union_type == struct B) {
               /** decode B's struct*/
       } 
       else {
               /** decode C strcut */
       }
}`

**Comment by soumagne** [comment]
In that case we don't have macros that automatically generate that so you'll have the write the encode/decode code by hand which is perfectly fine too, just pass pointers to those routines to `HG_Register()`.
