### ISSUE TITLE
Provide a macro to get NA version

### ISSUE THREAD

**Issue by mdorier** [mercury-hpc/mercury#569]
A recent commit changed the prototype of the `NA_Mem_register`, which we use in MoNA. It would be nice to either have a way of detecting the API version of NA at compile time to use the right form of the function, or to leave the old version of `NA_Mem_register` for backward compatibility and provide a new function (`NA_Mem_register_on_device`, `NA_Mem_register2`, or something else) for the "extended" version of takes a device id.

Alternatively, having the NA version in [mercury-config.cmake.in](https://github.com/mercury-hpc/mercury/blob/master/CMake/mercury-config.cmake.in) would work as well (at least for MoNA) since cmake could get the version of NA.

**Comment by soumagne** [comment]
I did add the NA versions as part of that last PR, it's in na_config.h now. The NA version was bumped to 3.0.0. There are now separate versions for HG and NA libraries.

**Comment by soumagne** [comment]
When you include na.h, you can now use NA_VERSION_MAJOR macros etc to check for the version.

**Comment by mdorier** [comment]
Ah I missed that, thanks!
