### ISSUE TITLE
Does the project support windows?

### ISSUE THREAD

**Issue by jspanchu** [mercury-hpc/mercury#614]
**Describe the bug**
Tried to build on windows with VS2022 and got a couple errors. Is there a known workaround for windows? From [this issue](https://github.com/mercury-hpc/mercury/issues/80), it seems like windows builds were possible back in 2016.

Here are some of the errors I could find.
1. [`mercury_log.c:124`](https://github.com/mercury-hpc/mercury/blob/master/src/util/mercury_log.c#L124) - C2099 initializer is not a constant
```bash
[build]   mercury_log.c
[build] C:\Users\jspan\projects\mercury\src\util\mercury_log.c(124): error C2102: '&' requires l-value [C:\Users\jspan\projects\mercury\build\src\util\mercury_util.vcxproj]
[build] C:\Users\jspan\projects\mercury\src\util\mercury_log.c(124,60): error C2099: initializer is not a constant [C:\Users\jspan\projects\mercury\build\src\util\mercury_util.vcxproj]
```
Even if I forced my way around that by using NULL in the initializer {}, there are more errors with some includes.
2. `na_ip.h` - sys/socket.h is not found
3. `na_ip.c` - ifaddrs.h, net/if.h, netdb.h are not found

**To Reproduce**
1. Build libfabric using the .sln file from their repository.
1. Run cmake and build on windows.

**Platform (please complete the following information):**
 - Windows 11
 - Compiler version: [VS2022, cl.exe version 19.33.31629 for x64
 - Dependency version [e.g. libfabric@main]

**Comment by soumagne** [comment]
We've always kept windows support as a possibility, without really committing to supporting it as we've never really had any user who asked for it. It's not regularly tested but most modules use wrappers and platform independent code so it should not be that difficult to fix. I had built it with MSVC in the past so yes it used to build at some point. It's very likely that the last bits that got introduced (log, NA IP) just broke some of it.

**Comment by soumagne** [comment]
Previous commit fixes all the build issues on windows and enables logging as well, the OFI plugin can also now be built on windows. There is a bit more work that would need to be done to disable or enable the wait fd feature and also to potentially enable the `netdir` provider on windows but everything should now be in better shape if anyone wants to pick this up again in the future.
