### ISSUE TITLE
Wrong version in mercury_config.h

### ISSUE THREAD

**Issue by Zhang690683220** [mercury-hpc/mercury#628]
**Describe the bug**
The main branch still has the version 2.1.0 in its generated mercury_config.h , which finally results in some function in the margo is not compiled.

```
/* Reflects major releases of Mercury */
#define HG_VERSION_MAJOR 2
/* Reflects any API changes */
#define HG_VERSION_MINOR 1
/* Reflects any library code changes */
#define HG_VERSION_PATCH 0

```

**To Reproduce**
Just simply build the latest commit from the source and install it. Check the mercury_config.h

**Expected behavior**
It should be at least 2.2.0 now.

**Screenshots**

**Platform (please complete the following information):**
 - PC with ubuntu 20.04
 - Compiler version: gcc/11.1.0
 - Plugin and protocol used OFI
 - Dependency version libfabric 1.15.1

**Additional context**

**Comment by soumagne** [comment]
The version number gets picked up from either from version.txt or from the git tag. Make sure if you are using git that you do a `git pull --tags`

**Comment by Zhang690683220** [comment]
Oh cool. It works now. Thank you.
