### ISSUE TITLE
NA_OFI/VERBS: Question about memory allocation

### ISSUE THREAD

**Issue by AdjoiningCat** [mercury-hpc/mercury#629]
Hi,

I did a test on a node with 4050 clients and 1 server, but only 4025 clients work properly, the other clients all report -61 while calling HGClass::new_with_opt, and libfabric report error : ibv_create_cq: Invalid argument(22) or ibv_create_qp: Cannot allocate memory(12).
I checked ulimit -l, it's unlimited, and my available memory is more than 350g.
The current count of qp or cq are both not up to the limit, and there are no error message in dmesg output.
My endpoint is RXM. I wonder is there any other resources will be created inside mercury except the resources required for communication between the client and server?

Thanks in advance for your precious time!

> mercury version: v2.1.0
libfabric version: v1.13.2

> env: 
   FI_PROVIDER="verbs"
   FI_VERBS_IFACE=ens800f0
   FI_VERBS_DEVICE_NAME=mlx5_2
   FI_VERBS_GID_IDX=3
   FI_VERBS_TX_SIZE=2
   FI_VERBS_RX_SIZE=2
   FI_UNIVERSE_SIZE=4050
   FI_OFI_RXM_BUFFER_SIZE=4096
   FI_OFI_RXM_MSG_TX_SIZE=4       
   FI_OFI_RXM_MSG_RX_SIZE=4
   FI_OFI_RXM_TX_SIZE=1
   FI_OFI_RXM_RX_SIZE=1

**Comment by soumagne** [comment]
Nothing inside mercury would be created that interferes with Libfabric's CQ creation, the main variable for OFI is FI_UNIVERSE_SIZE that determines the size of the CQ. I think you might have reached some limit, I'm not sure I fully understand your use case though, are all these clients on a single node ? If the clients do not communicate between each other, you should not need to set FI_UNIVERSE_SIZE to a large value.

**Comment by AdjoiningCat** [comment]
Yes, my clients and the server are all on the same single node. And I have tried to set FI_UNIVERSE_SIZE to 1 after my server were up, it helps reducing some memory, but it doesn't change the number of successful clients.

**Comment by soumagne** [comment]
Closing for now as I think this is either a libfabric issue or a hardware limit issue and this is tracked in https://github.com/ofiwg/libfabric/issues/8256. Feel free to re-open if needed.
