### ISSUE TITLE
automatically bump HG_LOG_SUBSYS when HG_LOG_LEVEL is set

### ISSUE THREAD

**Issue by carns** [mercury-hpc/mercury#634]
**Is your feature request related to a problem? Please describe.**

See https://github.com/mochi-hpc/mochi-thallium/issues/7#issuecomment-1379100285.  The log subsys is not implicitly changed in response to the log level when set via env variable, but it is when set by library API, if I understand correctly.  

**Describe the solution you'd like**

It would probably be better if they were consistent, so that users who want to see non-fatal error messages can get there with one environment variable.

**Describe alternatives you've considered**

We are going to address this in Margo via https://github.com/mochi-hpc/mochi-margo/issues/233 (we would prefer a higher default log level for our use case anyway so we may as well take explicit control over both the log level and log subsys for our purposes), just noting that maybe the inconsistency between the env variables and and programmatic API might be a good thing to fix independently at the Mercury level for non-Margo users.

**Comment by soumagne** [comment]
I fixed that just now, setting `HG_LOG_LEVEL` without setting `HG_LOG_SUBSYS` will be equivalent to setting `HG_LOG_SUBSYS=hg_all` (meaning all subsys enabled)
