### ISSUE TITLE
hg_core_recv_input_cb error with cci/tcp transport

### ISSUE THREAD

**Issue by carns** [mercury-hpc/mercury#66]
When I use the CCI/TCP transport in Mercury with a client and server that each have a separate thread dedicated to drive HG_Progress(), I get the following error on the server side when the RPC arrives:

```
HG: Error in /home/pcarns/working/src/mercury/src/mercury_core.c:1178
 # hg_core_recv_input_cb(): Buffer size and actual transfer size do not match
```

If I look at it in a debugger I see this:

```
1176	    if (callback_info->info.recv_unexpected.actual_buf_size
(gdb) 
1178	        HG_LOG_ERROR("Buffer size and actual transfer size do not match");
(gdb) print callback_info->info.recv_unexpected.actual_buf_size
$1 = 1488
(gdb) print hg_handle->in_buf_size
$2 = 8988
```

I'll dig into this more, but I'm not sure off the top of my head what to make of this.  It can be reproduced with one of the Examples/src example programs:

```
$ cat test.conf
[lo]
transport = tcp
ip = 127.0.0.1
default = 1
port = 1234
$ export CCI_CONFIG=test.conf
$ ./hg_example_rpc_server
# then in another terminal
$ ./hg_example_rpc_client
```

The standard test suite passes, though.

**Comment by soumagne** [comment]
Hmm not sure either like this but callback_info->info.recv_unexpected.actual_buf_size seems to be correct for CCI if I remember correctly; hg_handle->in_buf_size seems weird

**Comment by carns** [comment]
If I simply comment out that if() block, then the test program gets past that point and appears to transmit valid data in the RPC request structure.  Is it possible that it is valid for the actual_buf_size to be smaller than the in_buf_size in some cases, or are they supposed to exactly match?  Or is that just luck?  :)

**Comment by soumagne** [comment]
They should match because it is the size of an unexpected message, although I see now line 933:
    hg_handle->in_buf_size = NA_Msg_get_max_expected_size(na_class);
Can you please try to change it to `NA_Msg_get_max_unexpected_size(na_class);` ?

**Comment by soumagne** [comment]
I don't think that's the reason because I hope we would have noticed that before... :\

**Comment by carns** [comment]
I tried the change but I get the same result (and the same values in those variables when I check with a debugger).

**Comment by soumagne** [comment]
OK yes no surprise. Do you mean that in_buf_size is really initialized to 8988 bytes? I've always thought that the size with CCI was smaller than that...

**Comment by carns** [comment]
If I break the client on NA_Msg_send_unexpected(), I can see that 1488 bytes *is* the size of the unexpected msg that it is sending:

```
Breakpoint 1, NA_Msg_send_unexpected (na_class=0x62c010, context=0x62eee0, 
    callback=0x40f580 <hg_core_send_input_cb>, arg=0x7fffec000b80, 
    buf=0x7fffec001000, buf_size=1488, dest=0x62fad0, tag=1, 
    op_id=0x7fffec000bf8) at /home/pcarns/working/src/mercury/src/na/na.c:894
894	{
```

It seems like Mercury would be posting a maximum size for unexpected messages, but the sender may elect to send less?  If that's the problem then I'm not sure why I'm only seeing this now.  Maybe I have updated too many things at once...

**Comment by soumagne** [comment]
OK. No 1488 is the maximum size of an unexpected message with CCI so this is correct

**Comment by soumagne** [comment]
If I attach the debugger to the server, the handles are created with a buffer size of 1488, so we need to find out where the 8988 comes from...

**Comment by carns** [comment]
Well, if I break on na_cci_msg_get_max_unexpected_size(), it is returning 8988.  Then when the client goes to send this RPC request it is only sending 1488 bytes.  Are you saying that Mercury is supposed to always round up outbound requests to the maximum unexpected size?  Or can transports do "short" recvs in this case?

**Comment by soumagne** [comment]
Yes we can do short recvs, we just need to remove that check then, well or check that it is less than the buffer size

**Comment by carns** [comment]
Ok.  I can check what's going on in this case when we use the BMI transport too before we change anything.  It seems like I should have hit this already; BMI should be doing short recvs as well, I think...

**Comment by soumagne** [comment]
OK. I'm also curious to know why CCI defines the size to 8988 in your case... I always get 1488 on my machine.

**Comment by carns** [comment]
Ok, the main underlying problem here was that my client program and server program disagreed on the maximum unexpected message size.  I think CCI is choosing this based on MTU for the TCP transport; I had bound the server to a localhost address which had a larger MTU, while on the client I didn't specify an interface and it chose the first one (eth0) with a smaller MTU.

I resolved my problem by using this configuration for the client (I'm trying to test over loopback right now):

```
$ cat cci-client.conf 
[lo]
transport = tcp
default = 1
interface = lo
```

**Comment by soumagne** [comment]
OK thanks! Well we should also see if we can fix the short receive though.

**Comment by carns** [comment]
Yeah, I looked at this closer and confirmed that the reason I observed this bug is that he unexpected send is much larger than it should be; I opened that up as a separate ticket.  I can dig into that further while I have a good test case ready.
