### ISSUE TITLE
hg_proc_ type add double and float type

### ISSUE THREAD

**Issue by jin-zhengnan** [mercury-hpc/mercury#692]
I constructed a structure that contains the double type，like this
MERCURY_GEN_PROC(cublasDgemm_v2_in,
                ((uint64_t)(handle))\
                ((int32_t)(transa))\
                ((int32_t)(transb))\
                ((int32_t)(m))\
                ((int32_t)(n))\
                ((int32_t)(k))\
                ((double)(alpha))\
                ((uint64_t)(A))\
                ((int32_t)(lda))\
                ((uint64_t)(B))\
                ((int32_t)(ldb))\
                ((double)(beta))\
                ((uint64_t)(C)) \
                ((int32_t)(ldc)))
When I encode and send fail ，detai linfo is below： 
# [22327.889158] mercury->hg: [error] gerrit/mercury-2.2.0/src/mercury.c:635
 # hg_set_struct(): Could not encode parameters
Caught signal 11 (Segmentation fault: address not mapped to object at address 0x7f021a52c9a0)
==== backtrace (tid:  57794) ====
 0 0x0000000000012c20 .annobin_sigaction.c()  sigaction.c:0
 1 0x0000000000005df9 HG_Error_to_string() gerrit/mercury-2.2.0/src/mercury.c:976
 2 0x0000000000008401 HG_Forward()  gerrit/mercury-2.2.0/src/mercury.c:2003
 3 0x0000000000055495 send_cublasdgemm_v2()  ???:0
 4 0x000000000007d9e7 cublasDgemm_v2()  ???:0

and I find   only  below type is defined，

#define hg_proc_int8_t   hg_proc_hg_int8_t
#define hg_proc_uint8_t  hg_proc_hg_uint8_t
#define hg_proc_int16_t  hg_proc_hg_int16_t
#define hg_proc_uint16_t hg_proc_hg_uint16_t
#define hg_proc_int32_t  hg_proc_hg_int32_t
#define hg_proc_uint32_t hg_proc_hg_uint32_t
#define hg_proc_int64_t  hg_proc_hg_int64_t
#define hg_proc_uint64_t hg_proc_hg_uint64_t

/* Map mercury common types */
#define hg_proc_hg_bool_t hg_proc_hg_uint8_t
#define hg_proc_hg_ptr_t  hg_proc_hg_uint64_t
#define hg_proc_hg_size_t hg_proc_hg_uint64_t
#define hg_proc_hg_id_t   hg_proc_hg_uint32_t

/* Map hg_proc_raw/hg_proc_memcpy to hg_proc_bytes */
#define hg_proc_memcpy hg_proc_raw
#define hg_proc_raw    hg_proc_bytes

can you add double and float type for this？

**Comment by soumagne** [comment]
closing as we currently only choose to define fixed-size type primitives (with the addition of string types for convenience).
