### ISSUE TITLE
Add shared memory plugin to NA

### ISSUE THREAD

**Issue by soumagne** [mercury-hpc/mercury#75]
(updated 4/15)
###### Why do we want a shared-memory plugin for mercury
- CCI's handling of shared memory transport is explicit and not
  transparent to user
- How much of CCI shared-memory plugin can we re-use? could also try to
  create another endpoint using CCI and make it use shm for a secondary
  NA plugin. Although all plugins would be required to use CCI for
  shared-memory.
- Other libraries such as libfabric may also support shared memory
  optimization in the future: https://github.com/ofi-cray/libfabric-cray/issues/460
###### Shared memory plugin requirements
- [x] Transparent use (i.e. ability to use the same address for both 
  conventional and shared memory communication)
- [x] Ability to make progress on conventional and shared memory 
  communication simultaneously without busy waits
- [x] Reuse of existing shared memory technology and concepts to the degree 
  possible
###### Technical issues
- Determine when to use the shared-memory plugin 
  - Shared memory plugin can be selected by hostname or if the shared
    memory address string matches with target
  - Must first add ability to run 2 NA plugins for one HG class
- Multiplexing question / how to make progress on multiple plugins
  - Use file descriptor + epoll / progress (maybe more work so can
    defer this and use another temporary solution for now or start by
    adding it for the shared-memory plugin)
  - Don't want to busy wait
- Shared-memory transfers
  - CCI uses CMA/XPMEM and falls back to shm
  - Look at what mpich does and ownership passing paper
###### Action items
- [x] Look at MPICH nemesis
- [x] Look at ownership passing paper

**Comment by carns** [comment]
:+1: one vote for making it implicit :-)

It would be nice if Mercury could determine if a peer is on the same node and silently switch to a shared memory transport in that case.  This would also be consistent with the mechanism that Mercury already has in place to short circuit RPCs issued to the local process.
