### ISSUE TITLE
Changes to HG_RETURN_VALUE breaks API

### ISSUE THREAD

**Issue by mdorier** [mercury-hpc/mercury#766]
This commit https://github.com/mercury-hpc/mercury/commit/80869e0e67a39b772e4477d37445e30b4ff89eef breaks our Mochi stack. Thallium uses `HG_RETURN_VALUES` and expect `X` to take 1 argument. Would it be possible to introduce an `HG_RETURN_VALUES2` if Mercury now needs it to take 2 arguments, but leave `HG_RETURN_VALUES`? Otherwise this will force all the versions of thallium up to this point to become incompatible with future versions of Mercury, and all future versions of thallium to become incompatible with older versions of Mercury.

**Comment by soumagne** [comment]
Oh great, I just see your issue now and I went ahead today to create the release 🫤 I was not expecting that someone was using that directly... well I will need to see what I can do. Just curious, what are you using the HG_RETURN_VALUES macro for ?

**Comment by soumagne** [comment]
I guess I'll just retag and remake a release with that fix on Monday...

**Comment by mdorier** [comment]
I'm using it here: https://github.com/mochi-hpc/mochi-thallium/blob/main/include/thallium/margo_exception.hpp#L47 to generate the name of the error code when throwing exceptions.

**Comment by mdorier** [comment]
Yeah I should have.

**Comment by soumagne** [comment]
Fixed but as a heads-up I'll have to address this properly in a 3.0 release so you should start using that routine instead :)

**Comment by mdorier** [comment]
Will do, thanks :-)
