### ISSUE TITLE
error messages on shutdown

### ISSUE THREAD

**Issue by carns** [mercury-hpc/mercury#88]
[mercury-shutdown.zip](https://github.com/mercury-hpc/mercury/files/203417/mercury-shutdown.zip)

Example program attached.  When shutting down Mercury on the server side, using the na_cci plugin with tcp, I get the following error messages even if no communication has been performed:

NA: Error in /home/pcarns/working/src/mercury/src/na/na.c:499
 # NA_Context_destroy(): Completion queue should be empty
HG: Error in /home/pcarns/working/src/mercury/src/mercury_core.c:988
 # hg_core_finalize(): Could not destroy NA context
HG: Error in /home/pcarns/working/src/mercury/src/mercury_core.c:2198
 # HG_Core_finalize(): Cannot finalize HG core layer

The problem appears to be that the HG_Context_destroy() is causing the pending NA unexpected recv operations to be cancelled, but is not waiting on completion of those cancellation operations.  During shutdown it therefore detects that the NA completion queue is not empty.

**Comment by soumagne** [comment]
OK I fixed it in my topic_cancel, hopefully will merge soon
