### ISSUE TITLE
NA CCI: cannot make progress using cci+tcp

### ISSUE THREAD

**Issue by jiayulu** [mercury-hpc/mercury#91]
Using cci+tcp, HG_Hl_addr_lookup_wait() and the na_addr_lookup_wait() wrapper does not return. Further investigation shows that my code is hanging inside NA_Progress(). Have you seen this issue? Do you have a working example using CCI + TCP? Thanks!

**Comment by soumagne** [comment]
Hmmm are you doing blocking progress?

**Comment by jiayulu** [comment]
Blocking progress? I only found one function to make progress: NA_Progress(). I didn't create a separate thread to call NA_Progress() though.

**Comment by soumagne** [comment]
I mean, are you passing MAX_IDLE_TIME as a timeout?

**Comment by jiayulu** [comment]
Yes. I tried MAX_IDLE_TIME which is 3600*1000.  I also tried 500 and 1000, HG_Hl_addr_lookup_wait() and NA_Progress() return in this case but no progress is made.

**Comment by soumagne** [comment]
That seems weird, why are you calling both both NA_Progress and HG_Hl_addr_lookup_wait() ?

**Comment by jiayulu** [comment]
I am not calling them at the same time. I tried na_addr_lookup_wait() and HG_hl_addr_lookup_wait() seperately.

**Comment by soumagne** [comment]
Could you please send me an example of what you're doing? Does it happen only with CCI?

**Comment by jiayulu** [comment]
yes it only happens with cci+tcp. bmi+tcp works fine. let me see if I can get you an example.

**Comment by soumagne** [comment]
One difference with BMI is that CCI will try to connect whereas BMI only establishes connection at the time of communication. Is it possible that you're trying to connect to a target that is not reachable? Which string are you passing to lookup_wait? This may be related to the problem that @carns described in the pull request #73
