### ISSUE TITLE
NA CCI: free accepted addresses

### ISSUE THREAD

**Issue by soumagne** [mercury-hpc/mercury#92]
When CCI receives a new connection request event, the CCI plugin allocates a new address that gets then passed through cci_accept(). However disconnection is local. Unless I missed something, there should be a way of freeing the allocated addresses somehow (and not only when finalizing, which I added in commit 8522f9dc70560268ef699c5efeddaf4b79de7710).
Scott (@scottatchley), do you have any recommendations?

**Comment by scottatchley** [comment]
> On Apr 26, 2016, at 5:43 PM, Jerome Soumagne <notifications@github.com> wrote:
> 
> When CCI receives a new connection request event, the CCI plugin allocates a new address that gets then passed through cci_accept(). However disconnection is local. Unless I missed something, there should be a way of freeing the allocated addresses somehow (and not only when finalizing, which I added in commit 8522f9d).
> Scott (@scottatchley), do you have any recommendations?

Let me take a look.

Scott

**Comment by soumagne** [comment]
Ok thanks!

**Comment by scottatchley** [comment]
Hi Jerome,

How does the user indicate that an address is no longer needed?

The na_cci message headers have a “bye” bit to indicate that the sender indicates that he intends to close the connection, but we do not use it.

Perhaps in addr_decref(), if the count would go to zero, instead of freeing the addr, we could set a closing/disconnect flag and send a “bye” message to the peer. When the send completes, we call addr_decref() and if the closing/disconnect flag is set, then free it.

Thoughts?

Scott

**Comment by soumagne** [comment]
This is indicated when NA_Addr_free is called. NA_Addr_free is called on na_addr_t addresses that are created by NA_Addr_lookup, NA_Msg_recv_unexpected, NA_Addr_dup and NA_Addr_self.

Hmmm ok yes I think that would work and prevents from doing garbage collection of addresses. But then the problem is that we will be disconnecting everytime NA_Addr_free is called, which is maybe not the most efficient way of doing things as ideally connection would be closed when  a connection is no longer needed after a certain timeout. If the origin sends a bye message and we receive it in the main progress loop where we can then decref/set the closing flag, that would work for now at least.

**Comment by scottatchley** [comment]
> On May 6, 2016, at 11:21 AM, Jerome Soumagne <notifications@github.com> wrote:
> 
> This is indicated when NA_Addr_free is called. NA_Addr_free is called on na_addr_t addresses that are created by NA_Addr_lookup, NA_Msg_recv_unexpected, NA_Addr_dup and NA_Addr_self.
> 
> Hmmm ok yes I think that would work and prevents from doing garbage collection of addresses. But then the problem is that we will be disconnecting everytime NA_Addr_free is called, which is maybe not the most efficient way of doing things as ideally connection would be closed when a connection is no longer needed after a certain timeout. If the origin sends a bye message and we receive it in the main progress loop where we can then decref/set the closing flag, that would work for now at least.

For every operation (or a set of chained operations), are you saying that the client does:

NA_Addr_lookup()
<one or more ops>
NA_Addr_free()

then a short time later the cycle repeats?

Likewise, on the server:

NA_Msg_recv_unexpected()
<one or more ops>
NA_Addr_free()

for every unexpected message?

Is there no call to say that I do not intend to talk to that address any time soon?

**Comment by soumagne** [comment]
Yes this is what would happen in a common scenario. Hmm no we don't have a call that tells that... maybe something that we could consider having or as an extra parameter to NA_Addr_free... though I'm not sure this is the way we want to go... It was in our mind that we would let the plugin handle that kind of things and start closing connections, either after exceeding a maximum number of open connections or after an inactivity timeout (so that upper layers do not have to handle that and lookup would re-establish the connection if needed). Adding a parameter to NA_Addr_free for example to say that we don't intend to talk to that address again may simplify things but then delegates that task to the user I think...

**Comment by scottatchley** [comment]
> On May 6, 2016, at 1:36 PM, Jerome Soumagne <notifications@github.com> wrote:
> 
> Yes this is what would happen in a common scenario. Hmm no we don't have a call that tells that... maybe something that we could consider having or as an extra parameter to NA_Addr_free... though I'm not sure this is the way we want to go... It was in our mind that we would let the plugin handle that kind of things and start closing connections, either after exceeding a maximum number of open connections or after an inactivity timeout (so that upper layers do not have to handle that and lookup would re-establish the connection if needed). Adding a parameter to NA_Addr_free for example to say that we don't intend to talk to that address again may simplify things but then delegates that task to the user I think...

If I described the correct flow, then the current code will be creating/freeing addresses a lot when the last internal call to addr_decref() is called or am I missing something?

**Comment by soumagne** [comment]
On the client we would not do a lookup for every operation we forward, unless the structure of the code does not permit it and the client may also do that address management itself eventually. On the server yes that's potentially where there are more create/free of addresses because this is what recv_unexpected returns back, although it's handled differently in the CCI plugin because the addresses are created at the time a connection is accepted.
With the patch I had added in the CCI plugin, what would happen in the current code is that the accepted addresses on the server would only be freed when finalize is called, which could be an issue if we have a lot of connections/disconnections.

**Comment by scottatchley** [comment]
> On May 6, 2016, at 2:02 PM, Jerome Soumagne <notifications@github.com> wrote:
> 
> On the client we would not do a lookup for every operation we forward, unless the structure of the code does not permit it and the client may also do that address management itself eventually. On the server yes that's potentially where there are more create/free of addresses because this is what recv_unexpected returns back, although it's handled differently in the CCI plugin because the addresses are created at the time a connection is accepted.
> With the patch I had added in the CCI plugin, what would happen in the current code is that the accepted addresses on the server would only be freed when finalize is called, which could be an issue if we have a lot of connections/disconnections.

I guess I am still missing something.

On the client, is every NA_Addr_lookup() followed eventually by a NA_Addr_free()? If yes, do we want to incur a connection handshake for every lookup? If not, you want NA_Addrs and the underlying CCI connection to go away after some time?

On the server, replace unexpected receive for lookup and ask the same question?

It seems that we want to avoid handshakes for each (set of) operation(s) and we want automatic garbage collection, yes? :-)

**Comment by soumagne** [comment]
NA_Addr_lookup will be followed by a NA_Addr_free, since _lookup_ is not considered as _connect_. It may connect at this time but it may just re-use an opened connection too. Or it may also do what BMI does, in which case lookup does not initiate any connection and it only tries to connect when communication is started. So no ideally we do not want to incur a connection handshake for every lookup and yes we want the NA_Addrs and the underlying CCI connection to go away after some time.

Same for the server I think... although it seems that the server does not really decide anything and only accepts new connections in that case.

Yes exactly :) ideally we'd like to have garbage collection of addresses and avoid handshakes.

**Comment by scottatchley** [comment]
> On May 6, 2016, at 2:23 PM, Jerome Soumagne <notifications@github.com> wrote:
> 
> NA_Addr_lookup will be followed by a NA_Addr_free, since lookup is not considered as connect. It may connect at this time but it may just re-use an opened connection too. Or it may also do what BMI does, in which case lookup does not initiate any connection and it only tries to connect when communication is started. So no ideally we do not want to incur a connection handshake for every lookup and yes we want the NA_Addrs and the underlying CCI connection to go away after some time.
> 
> Same for the server I think... although it seems that the server does not really decide anything and only accepts new connections in that case.
> 
> Yes exactly :) ideally we'd like to have garbage collection of addresses and avoid handshakes.

Ok. :-)

We have never implemented keepalives, but that feature is meant to handle this case, maybe. If implemented, a transport would send a periodic message. If the receiver has closed the connection, the transport would generate a CCI_EVENT_KEEPALIVE_TIMEDOUT event rather than a SEND event with a failed status. The keepalive event includes a pointer to the now invalid connection, which has a pointer to the app-specific user context (i.e. NA_Addr).

If neither the client nor the server has closed the connection, keepalives probably do not help, which is why I said maybe above. :-)

If this is needed by all NAs, should we not implement this as a single service? Given that the upper NA layer has no notion of connections within the lower layer, we probably have to implement this in every NA lower layer. :-(

Scott

**Comment by soumagne** [comment]
Yes adding a single service for that purpose is definitely a possibility because yes that is something that will likely be needed by other NAs (although BMI is an exception I think as it handles that internally).
